import Foundation
import Network
import OSLog
import SwiftUI
import DeskPairShared

/// A remote desktop client that fails silently cannot be supported: "my keyboard does nothing" has to be
/// answerable from a log the user can collect, not from a debugger attached to their phone.
let sessionLog = Logger(subsystem: "com.sunllo.deskpair", category: "session")

/// Holds the session and turns it into something SwiftUI can render.
///
/// Everything that could be got wrong about the protocol lives in the Kotlin module and is checked against
/// vectors generated by the desktop. This file only has to move frames to a layer and touches to a pointer.
@MainActor
final class SessionModel: ObservableObject {

    enum Phase: Equatable {
        case disconnected(error: String?)
        // A state rather than a sentence: the library has no business choosing what language this reads in.
        case connecting(progress: ConnectProgress)
        case connected(hostname: String, platform: String, transport: String, width: Int, height: Int, displays: Int)
        /// A terminal on the host is open; `terminal` is the session.
        case terminal(hostname: String)
    }

    @Published private(set) var phase: Phase = .disconnected(error: nil)

    /// Settings, favourites and secrets. Injected rather than built here so one store serves every screen.
    let store: AppStore

    private let client: DeskPair

    init(store: AppStore) {
        self.store = store
        client = DeskPair(
            deviceName: UIDevice.current.name,
            // The desktop already knows this string and draws an icon for it.
            platform: "iOS",
            version: "0.1.0",
            // Keychain-backed, so a pinned host key survives the app being closed and TOFU means something.
            pinnedKeys: store.pinnedKeys
        )
        watchNetwork()
    }

    private var session: RemoteSession?
    private weak var display: VideoDisplayView?

    /// Both directions of the clipboard. Incoming text lands on the pasteboard by itself; outgoing text
    /// waits for the user, because reading the pasteboard prompts them.
    private let pasteboard = Pasteboard()

    /// The host's sound. Kept whether or not it works, so the UI can say why it does not.
    private let audio = IosAudio()
    private lazy var audioSink = NativeAudioSinkAdapter(inner: audio)

    /// Wiring the audio's own complaint to something the user can read. A remote desktop that is silently
    /// silent is indistinguishable from one whose host is not playing anything.
    private func watchAudio() {
        audio.onProblem = { [weak self] reason in
            Task { @MainActor in self?.audioProblem = reason }
        }
    }

    /// Set when the host offered sound this device cannot play, for the UI to explain rather than stay mute.
    @Published private(set) var audioProblem: String?

    /// The same for the picture, which until now could be black with nothing said about why.
    @Published private(set) var videoProblem: String?

    /// Whether a frame has ever been drawn on this session.
    ///
    /// The session reaching `.connected` means the two ends have agreed -- on a codec, a size, a transport
    /// -- not that there is anything to look at yet. Those are seconds apart on a slow link, and on a host
    /// that cannot read its own desktop they never converge at all. The screen showed its black backdrop
    /// for the whole of that gap, which looks identical to a session that has broken.
    ///
    /// So the picture is not shown until it exists. Until then the screen says, in as many words, that it
    /// is waiting for one.
    @Published private(set) var hasPicture = false

    /// Set once waiting has gone on long enough to be worth explaining rather than merely animating.
    @Published private(set) var pictureIsLate = false

    /// How long is long enough. Short enough that nobody sits through it wondering, long enough that an
    /// ordinary first keyframe over a relay is never called late.
    private static let lateAfter = Duration.seconds(6)

    private var lateTimer: Task<Void, Never>?

    /// Back to waiting, and start the clock again.
    ///
    /// Called when a session opens and whenever the stream restarts underneath it -- a display switch, a
    /// resolution change, a codec renegotiation. Each of those blanks the picture for a moment, and each
    /// of them used to blank it to black with no explanation.
    @MainActor
    private func expectPicture() {
        hasPicture = false
        pictureIsLate = false
        lateTimer?.cancel()
        lateTimer = Task { @MainActor [weak self] in
            try? await Task.sleep(for: Self.lateAfter)
            guard let self, !Task.isCancelled, !self.hasPicture else { return }
            self.pictureIsLate = true
        }
    }

    /// The host's own round-trip estimate.
    ///
    /// `SessionObservers.roundTrip` has existed in the shared layer all along and nothing here called it,
    /// so the signal chip could only say "arriving" or "stalled" — while its own comment claimed the
    /// colour said how well. Android has had the three-step version since it was written.
    @Published private(set) var roundTripMillis: Int?

    /// What the host currently allows, so the screen can stop offering what it will refuse.
    @Published private(set) var permissions = HostPermissions(
        keyboard: true, clipboard: true, audio: true, file: true, restart: true)

    /// Which display the host confirmed it is sending, rather than which one was asked for.
    @Published private(set) var currentDisplay = 0

    /// The host's displays as they are now, with the modes each can be switched to.
    @Published private(set) var displays: [RemoteDisplay] = []

    /// Why the last resolution request was refused, for the screen panel to say so.
    @Published private(set) var resolutionFailure: String?

    /// The host's word on why it has no screen to show: asking its person, declined, stopped there.
    @Published private(set) var hostNotice: String?

    /// Whether there is anything to offer the host. iOS answers this without raising the paste prompt.
    var canSendClipboard: Bool { pasteboard.hasContent }

    // ---- the canvas: where the picture sits and how big it is drawn ----

    @Published private(set) var canvas: CanvasState = CanvasState.companion.initial()

    @Published private(set) var pointerMode: PointerMode = .touch
    @Published private(set) var remoteCursor: RemoteCursorState?
    @Published var showRemoteCursor = true

    private let touch = TouchInterpreter(slop: 12, scrollStep: 16)
    private lazy var cursorSink = NativeCursorSinkAdapter(inner: SwiftCursorSink(model: self))

    func setPointerMode(_ mode: PointerMode) {
        pointerMode = mode
        touch.mode = mode
    }

    /// The view showing the picture changed size — rotation, a keyboard, a split screen.
    func viewResized(_ size: CGSize) {
        canvas = canvas.resized(newWidth: Float(size.width), newHeight: Float(size.height))
    }

    /// Back to the whole desktop, centred. The escape hatch for a canvas panned into nowhere.
    func resetCanvas() {
        canvas = canvas.fitted()
    }

    func actualSize() {
        canvas = canvas.actualSize()
    }

    // The cursor arrives on the Kotlin side's own thread; these run on the main actor.

    func applyCursorShape(id: Int64, shape: CursorShape) {
        var state = remoteCursor ?? .empty
        // Bounded, because a long session crossing many window edges would otherwise keep every shape it
        // ever saw. Sixteen is far more than any desktop cycles through.
        if state.shapes.count >= 16 {
            state.shapes.removeValue(forKey: state.shapes.keys.first!)
        }
        state.shapes[id] = shape
        state.shapeId = id
        remoteCursor = state
    }

    func applyCursorPosition(x: Int, y: Int) {
        // The host's own report, not a guess: in relative mode it applies acceleration this side cannot
        // model, and any local estimate drifts within seconds.
        touch.cursor = HostPoint(x: Int32(x), y: Int32(y))
        var state = remoteCursor ?? .empty
        state.x = x
        state.y = y
        remoteCursor = state
    }

    func applyCursorShapeId(_ id: Int64) {
        guard var state = remoteCursor, state.shapes[id] != nil else { return }
        state.shapeId = id
        remoteCursor = state
    }

    private lazy var sink = NativeVideoSinkAdapter(inner: SwiftVideoSink(model: self))

    func attach(_ view: VideoDisplayView) {
        display = view
        view.onProblem = { [weak self] reason in
            Task { @MainActor in self?.videoProblem = reason }
        }

        // A display layer that has just been handed over has no parameter sets and no reference frame,
        // so it can use nothing until a keyframe arrives. Asking is cheaper than waiting for the host's
        // own schedule.
        refreshVideo()
    }

    /// Kept so a dropped session can be picked up again. A phone loses its network in lifts and tunnels,
    /// and making someone retype an address every time is how a useful tool becomes an uninstalled one.
    private var lastTarget: (target: String, password: String)?

    /// Whether the next attempt should go through the relay whatever the settings say.
    ///
    /// Set when a session dies on a punched path without the host having closed it. A hole punched
    /// through two NATs can complete a TCP handshake, carry a login and twenty seconds of video, and then
    /// stop passing anything in either direction -- the host sees no acknowledgements and eventually a
    /// read timeout, and this end sees a picture that froze. Nothing about that is visible when the
    /// connection is made, so it cannot be decided in advance; it can only be answered by the attempt
    /// after it. The relay is slower and costs somebody bandwidth, and it works.
    private var retryOverRelay = false

    /// Whether the home screen should offer to try the last session again.
    ///
    /// Stored rather than derived from `lastTarget`, which is set by every attempt and cleared by nothing:
    /// "Try again" therefore appeared after the first connection of the run and stayed for the rest of it,
    /// offering to undo a disconnection the user had just asked for. It follows the same rule the automatic
    /// retry does -- only a session that ended in a way nobody chose is worth coming back from -- so pressing
    /// stop, or a host closing the session politely, leaves nothing on screen to argue with.
    @Published private(set) var canReconnect = false

    /// A machine whose key has changed, waiting for somebody to say whether that was expected.
    @Published var keyChanged: KeyChange?

    /// What the prompt needs: which machine, the two fingerprints, and the password to reuse on the retry.
    struct KeyChange: Identifiable {
        let target: String
        let was: String
        let now: String
        let password: String
        /// Whether the attempt that met the new key was for a terminal, so the retry is one too.
        var terminal = false

        var id: String { target }
    }

    /// Accepts the new key and connects again.
    ///
    /// Forgetting the pin is what lets the next attempt through: the verifier records whatever it is
    /// offered when there is nothing on file, which is the same thing that happened the first time this
    /// machine was ever reached.
    func trustChangedKey(_ change: KeyChange) {
        store.pinnedKeys.forget(hostId: change.target)
        keyChanged = nil
        if change.terminal {
            openTerminal(target: change.target, password: change.password)
        } else {
            connect(target: change.target, password: change.password)
        }
    }

    func reconnect() {
        guard let last = lastTarget else { return }
        connect(target: last.target, password: last.password)
    }

    /// True when a session ended on a path that had been punched or made directly, rather than relayed.
    private static func wasDirect(_ transport: String) -> Bool {
        transport != "RELAY"
    }

    /// Whether a session ended for a reason the user did not choose, so the network coming back is worth
    /// acting on. Cleared by a deliberate disconnect, because "I pressed stop" is not something to undo.
    private var wantsRetry = false

    /// How many times this drop has been retried, so a host that is simply gone is not chased for ever.
    private var retries = 0

    /// Enough for a handover or a lift; few enough that a host that has gone is left alone.
    private static let maximumRetries = 3

    private let networks = NWPathMonitor()

    /// Comes back by itself when the network does.
    ///
    /// The comment on `reconnect` has always argued that retyping an address after every lift and tunnel is
    /// what makes someone uninstall a tool — and then the app shipped a button. The host gives up on a
    /// silent peer after thirty seconds, so this is a fresh session rather than a resumed one; what it
    /// saves is the typing, not the state.
    private func watchNetwork() {
        networks.pathUpdateHandler = { [weak self] path in
            guard path.status == .satisfied else { return }
            Task { @MainActor in
                guard let self, self.wantsRetry, self.retries < Self.maximumRetries else { return }
                if case .disconnected = self.phase {
                    self.retries += 1
                    self.reconnect()
                }
            }
        }
        networks.start(queue: DispatchQueue(label: "com.sunllo.deskpair.network"))
    }

    /// The last complete answer given to the host, so an update can restate it.
    private var preferences = SessionPreferences.companion.defaults()

    /// Asks the host for a different picture. An option it may decline, not a command.
    ///
    /// Restates every option, not just the quality: the host replaces its whole copy of them and
    /// re-derives the session's permissions, so anything left out comes back on. Sending three fields here
    /// used to re-enable the host's audio capture.
    func setQuality(_ quality: Quality) {
        guard let session else { return }
        preferences = preferences.doCopy(
            quality: quality,
            customBitrateKbps: preferences.customBitrateKbps,
            customFps: preferences.customFps,
            showRemoteCursor: preferences.showRemoteCursor,
            losslessRefinement: preferences.losslessRefinement,
            udpMedia: preferences.udpMedia,
            audioEnabled: preferences.audioEnabled,
            viewOnly: preferences.viewOnly,
            lockAfterSessionEnd: preferences.lockAfterSessionEnd
        )
        let wanted = preferences
        Task { try? await session.setPreferences(preferences: wanted) }
    }

    func switchDisplay(_ index: Int) {
        guard let session else { return }
        Task { try? await session.switchDisplay(index: Int32(index)) }
    }

    /// Asks the host to switch a display to one of its advertised modes, or back to its original.
    func setResolution(_ display: Int, _ resolution: RemoteResolution?) {
        guard let session else { return }
        Task { try? await session.setResolution(display: Int32(display), resolution: resolution) }
    }

    /// Connects to whatever the user typed.
    ///
    /// One entry point, because the home screen has one text field. Which kind of target it is comes from
    /// `Targets.isDirect`, ported from `PeerConnector.IsDirectTarget` so a string means the same thing here
    /// as it does on the desktop — including the part where a nine-digit id is recognised before anything
    /// tries to read it as an address.
    func connect(target typed: String, password: String, remember: Bool = false) {
        let target = Targets.shared.normalise(typed: typed)
        guard !target.isEmpty else { return }

        watchAudio()
        lastTarget = (target, password)
        canReconnect = false
        phase = .connecting(progress: .connecting)

        // Captured before the Task so the session and the model start from the same answer.
        let wanted = SessionPreferences.companion.from(settings: store.settings)
        preferences = wanted

        Task {
            do {
                // Which signalling server, resolved once per attempt. A code scanned for this desk wins
                // for this desk; otherwise a configured address wins; otherwise the portal is asked. An
                // address typed into the box needs none of this, which is why Targets.resolve still
                // decides what kind of target it is.
                let directory: NetworkDirectory
                if let scanned = store.scannedNetwork(target) {
                    directory = scanned
                } else {
                    directory = try await NetworkDirectoryClient.shared.resolve(settings: store.settings)
                }
                let opened = try await client.connect(
                    target: Targets.shared.resolve(
                        typed: target,
                        rendezvousServer: directory.rendezvous,
                        serverPublicKeyBase64: directory.publicKey,
                        // Either the setting asks for it, or the last attempt proved this network's
                        // punched path does not survive being used.
                        forceRelay: store.settings.forceRelay || retryOverRelay
                    ),
                    password: password.isEmpty ? nil : password,
                    sink: sink,
                    clipboard: pasteboard,
                    // A session that never asked for sound is never sent any, so this is a subscription
                    // rather than a mute button.
                    audio: store.settings.audioEnabled ? audioSink : nil,
                    cursor: cursorSink,
                    // What the settings screen has been collecting all along. Until now none of it reached
                    // a session: quality, custom bitrate and frame rate, the cursor option, the refinement
                    // switch and the UDP switch were stored, shown, and read by nobody.
                    preferences: wanted,
                    onProgress: { [weak self] progress in
                        Task { @MainActor in self?.phase = .connecting(progress: progress) }
                    },
                    resolutions: store.resolutionsFor(peer: target)
                )

                session = opened
                wantsRetry = false
                canReconnect = false
                retries = 0
                // Whatever path this one took, it worked; the next fresh attempt starts from the settings.
                retryOverRelay = false
                roundTripMillis = nil
                audioProblem = nil
                videoProblem = nil
                expectPicture()

                // Two more settings that never left the settings screen, and neither of them is the host's
                // business: how fingers are interpreted, and how the picture is framed.
                setPointerMode(store.settings.pointerMode == "mouse" ? .mouse : .touch)
                showRemoteCursor = store.settings.showRemoteCursor
                canvas = store.settings.fitToWindow ? canvas.fitted() : canvas.actualSize()
                if remember {
                    store.rememberPassword(target, password)
                }
                store.rememberConnection(
                    target: target, name: opened.host.hostname, platform: opened.host.platform)

                sessionLog.notice("connected to \(opened.host.hostname, privacy: .public) over \(opened.transport, privacy: .public)")
                follow(opened)
                let first = opened.host.displays.first
                phase = .connected(
                    hostname: opened.host.hostname,
                    platform: opened.host.platform,
                    // How the picture is arriving, not merely how the session was opened.
                    transport: opened.currentMediaPath ?? opened.transport,
                    width: Int(first?.width ?? 0),
                    height: Int(first?.height ?? 0),
                    displays: opened.host.displays.count
                )
            } catch {
                sessionLog.error("connect failed: \(error.localizedDescription, privacy: .public)")
                // A password that turns out to be wrong must not stay remembered, or the app would go on
                // failing silently with a stored value the user cannot see.
                if error is LoginRefusedException {
                    store.forgetPassword(target)
                }

                // The key this machine used to present is not the key it presents now. That is either a
                // reinstall or an impersonation, and only the person can tell which -- so they are asked,
                // here, where it happened. There used to be a list of fingerprints in settings for this,
                // which is a strange place to answer a question nobody knew they had been asked.
                if let changed = error as? HostIdentityChangedException {
                    keyChanged = KeyChange(
                        target: changed.hostId,
                        was: changed.pinnedFingerprint,
                        now: changed.offeredFingerprint,
                        password: password
                    )
                }

                // An attempt that never arrived is the one case where the button is the obvious next move.
                canReconnect = true
                phase = .disconnected(error: Self.describe(error))
            }
        }
    }

    /// Called from the Kotlin side on its own thread, so it hops to the main actor before touching the layer.
    ///
    /// The return value is always `true`, and that is not a shrug: the enqueue happens later, on the main
    /// actor, so at the moment this returns there is genuinely nothing to report. Recovery is handled here
    /// instead — `enqueue` says whether the layer took the frame, and a refusal asks the host for a
    /// keyframe directly.
    ///
    /// The previous version threw that answer away and claimed in a comment that "the decoder's own error
    /// path" would ask for one. There is no such path. The shared layer's automatic request
    /// (`RemoteSession.pump`, on `!accepted`) was therefore dead code on iOS, and coming back from the
    /// background could leave a frozen picture until the host's own keyframe interval came round.
    nonisolated func onFrame(data: Data, isKeyFrame: Bool, width: Int32, height: Int32, format: VideoFormat, vp9: Vp9Configuration?) -> Bool {
        Task { @MainActor in
            self.canvas = CanvasState.companion.forHost(previous: self.canvas, width: width, height: height)
            let accepted = self.display?.enqueue(frame: data, isKeyFrame: isKeyFrame, format: format, vp9: vp9) ?? false
            if accepted {
                // The first one that the layer takes is the moment there is something to look at. A frame
                // it refused is not a picture, so the waiting screen stays up rather than uncovering black.
                self.hasPicture = true
                self.pictureIsLate = false
                self.lateTimer?.cancel()
            } else {
                self.askForKeyFrame()
            }
        }

        return true
    }

    /// When the last keyframe was asked for, so a broken stream does not become a request storm.
    private var lastKeyFrameRequest = Date.distantPast

    /// A decoder that cannot use what it was given needs a fresh start, not the next inter frame.
    ///
    /// Throttled because a layer that has given up refuses every frame, and at sixty a second that would
    /// be sixty requests a second up a link that is already unwell.
    @MainActor
    private func askForKeyFrame() {
        guard Date().timeIntervalSince(lastKeyFrameRequest) > 1 else { return }
        lastKeyFrameRequest = Date()
        refreshVideo()
    }

    // MARK: - Gestures

    /// The fingers changed. Everything about what a gesture *means* lives in the shared interpreter; this
    /// only forwards what it decides, so the two apps cannot drift apart again.
    func onTouch(_ pointers: [Touch]) { apply(touch.update(pointers: pointers, canvas: canvas)) }

    func onDoubleTapDrag(_ at: CGPoint) {
        apply(touch.doubleTapDragStart(x: Float(at.x), y: Float(at.y), canvas: canvas))
    }

    func onTouchCancelled() { apply(touch.cancel()) }

    private func apply(_ outcomes: [TouchOutcome]) {
        guard !outcomes.isEmpty else { return }

        for outcome in outcomes {
            switch outcome {
            case let pan as TouchOutcomePanCanvas:
                canvas = canvas.panned(dx: pan.dx, dy: pan.dy)

            case let zoom as TouchOutcomeZoomCanvas:
                canvas = canvas.zoomed(factor: zoom.factor, focalX: zoom.focalX, focalY: zoom.focalY)

            case let pointer as TouchOutcomePointer:
                send { try await $0.sendPointer(
                    action: pointer.action,
                    button: pointer.button,
                    x: pointer.x,
                    y: pointer.y
                ) }

            case let move as TouchOutcomeRelativePointer:
                send { try await $0.sendPointer(action: .moveRelative, button: .none, x: move.dx, y: move.dy) }

            case let scroll as TouchOutcomeScroll:
                send { try await $0.sendPointer(action: .wheel, button: .none, x: 0, y: scroll.ticks) }

            default:
                break
            }
        }
    }

    private func send(_ body: @escaping (RemoteSession) async throws -> Void) {
        guard let session else { return }
        Task { try? await body(session) }
    }

    /// Zooms about the middle of the view, for a driven run — a pinch cannot be scripted on a simulator.
    func zoomForTest(_ factor: Float) {
        canvas = canvas.zoomed(factor: factor, focalX: canvas.viewWidth / 2, focalY: canvas.viewHeight / 2)
        sessionLog.notice("canvas now scale=\(self.canvas.scale) at=\(self.canvas.x),\(self.canvas.y)")
    }

    /// One pointer move through the real canvas, so a script can check the mapping against the host.
    func probeMove(_ at: CGPoint) {
        let host = canvas.toHost(viewX: Float(at.x), viewY: Float(at.y))
        send { try await $0.sendPointer(action: .move, button: .none, x: host.x, y: host.y) }
    }

    /// Asks the host for a fresh keyframe — the picture can be wrong without anything being broken.
    /// The scene is leaving the screen or back on it; see RemoteSession.setBackgrounded.
    func setBackgrounded(_ background: Bool) {
        session?.setBackgrounded(background: background)
    }

    func refreshVideo() {
        send { try await $0.refreshVideo(display: 0) }
    }

    // MARK: - Keyboard

    /// Modifiers the user has latched on the bar. A phone cannot hold Cmd and press S at once, so the bar
    /// holds it and the next key carries it.
    @Published private(set) var heldModifiers: Set<RemoteModifier> = []

    /// True while the app's own typing field has focus, so keys belong to it rather than to the host.
    var typingFieldFocused = false

    func toggleModifier(_ modifier: RemoteModifier) {
        if heldModifiers.contains(modifier) {
            heldModifiers.remove(modifier)
        } else {
            heldModifiers.insert(modifier)
        }
    }

    func press(_ key: RemoteKey) {
        guard let session else {
            sessionLog.error("cannot press a key: no session")
            return
        }
        let held = heldModifiers
        Task {
            do {
                try await session.sendKey(key: key, modifiers: held, pressed: nil)
            } catch {
                sessionLog.error("key failed: \(error.localizedDescription, privacy: .public)")
            }
            // Latched modifiers apply to one key, as sticky keys do: holding them across everything after
            // is never what someone meant.
            await MainActor.run { self.heldModifiers = [] }
        }
    }

    /// With a modifier latched, a single character is a shortcut rather than text: latch Cmd, type s, and
    /// the host receives Cmd+S. Sending the letter would type an s into whatever has focus.
    func type(_ text: String) {
        guard let session, !text.isEmpty else {
            sessionLog.error("cannot type: \(self.session == nil ? "no session" : "nothing to send", privacy: .public)")
            return
        }
        let held = heldModifiers

        // Kotlin's Char crosses as a UTF-16 unit, so a character outside the basic plane has no single
        // value to send — and no key on a keyboard either, which is why it falls through to text.
        if !held.isEmpty, text.count == 1, let unit = text.utf16.first, text.utf16.count == 1,
           Scancodes.shared.of(character: unit) != nil {
            Task {
                do {
                    try await session.sendShortcut(character: unit, modifiers: held)
                    sessionLog.debug("sent shortcut with \(held.count) modifier(s)")
                } catch {
                    sessionLog.error("shortcut failed: \(error.localizedDescription, privacy: .public)")
                }
                await MainActor.run { self.heldModifiers = [] }
            }
            return
        }

        Task {
            do {
                try await session.sendText(text: text)
                sessionLog.debug("sent \(text.count) character(s) of text")
            } catch {
                sessionLog.error("text failed: \(error.localizedDescription, privacy: .public)")
            }
        }
    }

    /// What became of the last picture offered, for the screen to show and then clear.
    @Published var imageOffer: ImageOffer?

    enum ImageOffer: Equatable {
        case sent(bytes: Int)
        /// The host already has it — the echo filter recognised it. Not a failure.
        case alreadyThere
        case failed
    }

    /// Offers this device's clipboard to the host. iOS raises its own "Allow Paste?" prompt on the read,
    /// which is why this is a button rather than something that happens by itself.
    ///
    /// A picture is looked for first: asking for text on an image-only pasteboard finds nothing, and the
    /// user who just copied a screenshot would be told there was nothing to send.
    func sendClipboard() {
        guard session != nil else { return }

        if pasteboard.hasImage, let png = pasteboard.readImage() {
            sendImage(png)
            return
        }

        guard let session, let text = pasteboard.read() else {
            sessionLog.notice("nothing on the pasteboard to send")
            return
        }

        Task {
            do {
                let sent = try await session.sendClipboardText(text: text)
                sessionLog.debug("clipboard offered: \(sent.boolValue ? "sent" : "already known to the host")")
            } catch {
                sessionLog.error("clipboard failed: \(error.localizedDescription, privacy: .public)")
            }
        }
    }

    /// Puts a picture on the host's clipboard, so it can be pasted there.
    ///
    /// Goes through NativeClipboard rather than the ByteArray-taking method: a Kotlin ByteArray crosses
    /// into Objective-C element by element, which is painful for a three megabyte screenshot.
    func sendImage(_ png: Data) {
        guard let session else { return }
        sessionLog.notice("offering a \(png.count)-byte picture to the host")

        Task {
            do {
                let sent = try await NativeClipboard.shared.sendImage(session: session, png: png)
                imageOffer = sent.boolValue ? .sent(bytes: png.count) : .alreadyThere
            } catch {
                sessionLog.error("picture failed: \(error.localizedDescription, privacy: .public)")
                imageOffer = .failed
            }
        }
    }

    /// Follows a session after it opens.
    ///
    /// The datagram channel is offered seconds after login, so the transport read at connect time is
    /// always the TCP one; and a session that drops used to leave the app on a frozen frame with no
    /// message and no way back.
    private func follow(_ opened: RemoteSession) {
        observations.forEach { $0.stop() }
        observations = []

        observations.append(SessionObservers.shared.mediaPath(session: opened) { [weak self] (path: String?) in
            guard let self else { return }
            if case let .connected(hostname, platform, _, width, height, displays) = self.phase {
                self.phase = .connected(
                    hostname: hostname,
                    platform: platform,
                    transport: path ?? opened.transport,
                    width: width,
                    height: height,
                    displays: displays
                )
            }
        })

        observations.append(SessionObservers.shared.roundTrip(session: opened) { [weak self] (rtt: KotlinInt?) in
            self?.roundTripMillis = rtt?.intValue
        })

        observations.append(SessionObservers.shared.permissions(session: opened) { [weak self] granted in
            self?.permissions = granted
        })

        observations.append(SessionObservers.shared.display(session: opened) { [weak self] (index: KotlinInt) in
            self?.currentDisplay = index.intValue
        })

        observations.append(SessionObservers.shared.displays(session: opened) { [weak self] (now: [RemoteDisplay]) in
            guard let self else { return }
            self.displays = now
            // The size the picture is framed for follows the display being shown.
            if case let .connected(hostname, platform, transport, _, _, _) = self.phase,
               self.currentDisplay < now.count {
                let shown = now[self.currentDisplay]
                self.phase = .connected(
                    hostname: hostname,
                    platform: platform,
                    transport: transport,
                    width: Int(shown.width),
                    height: Int(shown.height),
                    displays: now.count
                )
            }
        })

        observations.append(SessionObservers.shared.resolutionFailure(session: opened) { [weak self] (why: String?) in
            self?.resolutionFailure = why
        })

        observations.append(SessionObservers.shared.hostNotice(session: opened) { [weak self] (notice: String?) in
            self?.hostNotice = notice
        })

        // A stale picture, which recovers on its own — and, now, says so when it does.
        //
        // The parameter is `KotlinBoolean`, not `Bool`: a Kotlin primitive in a lambda position crosses
        // the bridge boxed, the same way `Int?` arrives as `KotlinInt?`.
        observations.append(SessionObservers.shared.stalled(session: opened) { [weak self] (stalled: KotlinBoolean) in
            self?.stalled = stalled.boolValue
        })

        observations.append(SessionObservers.shared.state(session: opened) { [weak self] (state: SessionState) in
            guard let self else { return }
            switch state {
            // Both end the session; the difference is only whether anyone expected it. `failure` carries
            // the host's own reason when it gave one, so a deliberate disconnect from the other end no
            // longer looks exactly like a severed cable.
            // Only a failure is worth coming back from. A host that closed the session politely has said
            // what it wants, and reconnecting over the top of that would be rude.
            case .failed:
                // A punched path that dies is a punched path to stop using.
                let direct = Self.wasDirect(opened.transport)
                self.retryOverRelay = direct
                self.wantsRetry = self.lastTarget != nil
                self.canReconnect = self.lastTarget != nil
                self.stalled = false

                // What a person can do something about, rather than what the socket said. The reason
                // underneath -- "recv failed: Resource temporarily unavailable" -- is a read that
                // returned nothing on a path that had stopped passing anything, which is true and is not
                // a sentence anybody should be shown.
                sessionLog.error("session failed: \(opened.failure ?? "-", privacy: .public)")
                self.phase = .disconnected(
                    error: String(localized: direct ? "session.droppedRetrying" : "session.dropped"))

                // Straight away, and only for the path that has just proved itself: the retry that waits
                // for the network to come back cannot help here, because nothing about the network
                // changed. The punch simply stopped carrying.
                if direct, self.retries < Self.maximumRetries, self.lastTarget != nil {
                    self.retries += 1
                    Task { @MainActor in
                        try? await Task.sleep(for: .milliseconds(600))
                        if case .disconnected = self.phase {
                            self.reconnect()
                        }
                    }
                }
            case .closed:
                // Politely closed from the other end, so there is nothing here to recover: the offer goes
                // away with the session, and the desk is still one tap away in the list.
                self.canReconnect = false
                self.stalled = false
                self.phase = .disconnected(
                    error: opened.failure ?? String(localized: "session.closedByHost"))
            default:
                break
            }
        })
    }

    private var observations: [Observation] = []

    /// The picture is older than the host's heartbeat. Distinct from the session having ended.
    ///
    /// This used to be set from `SessionState.failed` and never cleared, so once a session broke the
    /// warning stayed on screen through every subsequent healthy reconnection.
    @Published private(set) var stalled = false

    /// The open terminal, if the app is showing one instead of a desktop.
    @Published private(set) var terminal: TerminalModel?

    /// Opens a terminal on what the user typed. The same way to the host as `connect` -- the same server,
    /// the same password rules -- but a terminal connection, which asks for no picture and gets a shell.
    func openTerminal(target typed: String, password: String, remember: Bool = false, typing: String? = nil) {
        let target = Targets.shared.normalise(typed: typed)
        guard !target.isEmpty else { return }

        canReconnect = false
        phase = .connecting(progress: .connecting)
        Task {
            do {
                let directory: NetworkDirectory
                if let scanned = store.scannedNetwork(target) {
                    directory = scanned
                } else {
                    directory = try await NetworkDirectoryClient.shared.resolve(settings: store.settings)
                }
                let opened = try await client.connectTerminal(
                    target: Targets.shared.resolve(
                        typed: target,
                        rendezvousServer: directory.rendezvous,
                        serverPublicKeyBase64: directory.publicKey,
                        forceRelay: store.settings.forceRelay
                    ),
                    password: password.isEmpty ? nil : password,
                    // A first guess; the screen resizes it to what fits as soon as it is laid out.
                    columns: 80,
                    rows: 24,
                    onProgress: { [weak self] progress in
                        Task { @MainActor in self?.phase = .connecting(progress: progress) }
                    }
                )
                if remember {
                    store.rememberPassword(target, password)
                }
                store.rememberConnection(
                    target: target, name: opened.host.hostname, platform: opened.host.platform)

                sessionLog.notice("terminal on \(opened.host.hostname, privacy: .public) over \(opened.transport, privacy: .public)")
                let model = TerminalModel(opened)
                model.scripted = typing
                terminal = model
                phase = .terminal(hostname: opened.host.hostname)
            } catch {
                sessionLog.error("terminal failed: \(error.localizedDescription, privacy: .public)")
                if error is LoginRefusedException {
                    store.forgetPassword(target)
                }
                if let changed = error as? HostIdentityChangedException {
                    keyChanged = KeyChange(
                        target: changed.hostId,
                        was: changed.pinnedFingerprint,
                        now: changed.offeredFingerprint,
                        password: password,
                        terminal: true
                    )
                }
                phase = .disconnected(
                    error: Self.isTerminalRefusal(error) ? String(localized: "terminal.notAllowed") : Self.describe(error))
            }
        }
    }

    func closeTerminal() {
        terminal?.close()
        terminal = nil
        phase = .disconnected(error: nil)
    }

    /// The host did not grant a terminal. Checked on the bridged error as well, which is where Kotlin puts
    /// the exception it threw when the error reaches Swift as an `NSError`.
    private static func isTerminalRefusal(_ error: Error) -> Bool {
        (error as NSError).userInfo["KotlinException"] is TerminalNotAllowedException
            || (error as AnyObject) is TerminalNotAllowedException
    }

    func disconnect() {
        wantsRetry = false
        canReconnect = false
        let closing = session
        session = nil
        audio.stop()
        phase = .disconnected(error: nil)
        Task { try? await closing?.close(reason: "closed by user") }
    }


    /// What went wrong, in the reader's language. The shared module throws typed errors and English
    /// sentences; the sentence is for the log, the type is for this. Anything untyped is shown inside one
    /// localised frame with the English detail.
    static func describe(_ error: Error) -> String {
        if let version = error as? ProtocolVersionException {
            return version.side == ProtocolVersionSide.hostTooOld
                ? String(localized: "session.hostTooOld")
                : String(localized: "session.clientTooOld")
        }
        if let unreachable = error as? HostUnreachableException {
            switch unreachable.why {
            case UnreachableCause.unknownId: return String(format: String(localized: "session.unreachable.unknownId"), unreachable.hostId)
            case UnreachableCause.offline: return String(format: String(localized: "session.unreachable.offline"), unreachable.hostId)
            case UnreachableCause.serverBusy: return String(localized: "session.unreachable.busy")
            case UnreachableCause.noRelay: return String(format: String(localized: "session.unreachable.noRelay"), unreachable.hostId)
            default: return String(localized: "session.unreachable.noAnswer")
            }
        }
        if error is LoginRefusedException || error is HostIdentityChangedException {
            return error.localizedDescription
        }
        return String(format: String(localized: "session.failedDetail"), error.localizedDescription)
    }
}

/// The Kotlin side calls this; it exists because a Swift class cannot conform to a Kotlin interface and be
/// an ObservableObject on the main actor at the same time without the hop being explicit.
private final class SwiftVideoSink: NSObject, NativeVideoSink {
    private weak var model: SessionModel?

    init(model: SessionModel) {
        self.model = model
    }

    /// H.264 always; VP9 where VideoToolbox has a decoder for it, so a host that cannot encode H.264 can still be watched.
    var formats: Set<VideoFormat> {
        VideoDisplayView.decodesVp9 ? [VideoFormat.h264, VideoFormat.vp9] : [VideoFormat.h264]
    }

    // Swift's importer bridges the Kotlin NSData to Data, so the protocol requirement is spelled that way.
    func onFrame(data: Data, isKeyFrame: Bool, width: Int32, height: Int32, format: VideoFormat, vp9: Vp9Configuration?) -> Bool {
        model?.onFrame(data: data, isKeyFrame: isKeyFrame, width: width, height: height, format: format, vp9: vp9) ?? true
    }
}
