package com.sunllo.deskpair.crypto

import dev.whyoleg.cryptography.CryptographyAlgorithm
import dev.whyoleg.cryptography.CryptographyAlgorithmId
import dev.whyoleg.cryptography.CryptographyProvider
import dev.whyoleg.cryptography.DelicateCryptographyApi
import dev.whyoleg.cryptography.algorithms.AES
import dev.whyoleg.cryptography.algorithms.EC
import dev.whyoleg.cryptography.algorithms.ECDH
import dev.whyoleg.cryptography.algorithms.ECDSA
import dev.whyoleg.cryptography.BinarySize.Companion.bytes
import dev.whyoleg.cryptography.algorithms.HMAC
import dev.whyoleg.cryptography.algorithms.PBKDF2
import dev.whyoleg.cryptography.algorithms.SHA256

/**
 * Everything the protocol needs from cryptography, and nothing else.
 *
 * It is deliberately narrow. The protocol above it — the handshake transcript, the HKDF schedule, the
 * AES-GCM nonce discipline — is common code checked against vectors generated by the C# implementation, so
 * the only thing this layer decides is which library computes a primitive. If a backend turns out to be
 * unable to do one of these, it is replaced here and nothing above notices.
 *
 * The same code runs on Android and iOS; only which backend computes a primitive differs, and that is
 * declared per platform in [cryptographyProviders] rather than left to whatever happens to be on the path.
 * Being explicit matters here: Apple's Security.framework has no ECDH and no AES-GCM in a form this library
 * can reach, so iOS goes to CryptoKit first and falls back to Security only for what CryptoKit lacks. With
 * an implicit default that shows up as "Algorithm not found" at run time, on a phone.
 *
 * Only [secureRandomBytes] is per-platform beyond that, because the library exposes no randomness.
 *
 * Nothing here is written by hand. A hand-rolled AES or P-256 would be a far worse risk than any dependency.
 */
/** A freshly generated signing identity: the private half to keep, the public half to hand out. */
internal class EcdsaKeyPair(val privateKeyPkcs8: ByteArray, val publicKeySpki: ByteArray)

internal object Crypto {

    private val providers: List<CryptographyProvider> by lazy { cryptographyProviders() }

    /**
     * The first backend that implements this algorithm. The failure is loud and names the platform, because
     * the alternative is a connection that works everywhere except one device and nobody knows why.
     */
    private fun <A : CryptographyAlgorithm> algorithm(id: CryptographyAlgorithmId<A>): A =
        providers.firstNotNullOfOrNull { it.getOrNull(id) }
            ?: throw CryptoUnavailableException(
                "No cryptography backend on this platform implements $id. Tried: " +
                    providers.joinToString { it.name },
            )

    fun sha256(data: ByteArray): ByteArray =
        algorithm(SHA256).hasher().hashBlocking(data)

    fun hmacSha256(key: ByteArray, data: ByteArray): ByteArray =
        algorithm(HMAC)
            .keyDecoder(SHA256)
            .decodeFromByteArrayBlocking(HMAC.Key.Format.RAW, key)
            .signatureGenerator()
            .generateSignatureBlocking(data)

    fun randomBytes(count: Int): ByteArray = secureRandomBytes(count)

    /**
     * PBKDF2-HMAC-SHA256, the derivation a protocol-2 host names for its passwords.
     *
     * The backend does it where one can (the JDK, and CommonCrypto through the Apple provider); where
     * none can it is done here over [hmacSha256], which is the same arithmetic at the cost of one native
     * call per round. Slow is acceptable for a login; "Algorithm not found" on one platform is not.
     */
    fun pbkdf2Sha256(password: ByteArray, salt: ByteArray, iterations: Int, length: Int): ByteArray {
        require(iterations > 0) { "PBKDF2 needs at least one round." }
        val native = runCatching {
            algorithm(PBKDF2)
                .secretDerivation(digest = SHA256, iterations = iterations, outputSize = length.bytes, salt = salt)
                .deriveSecretToByteArrayBlocking(password)
        }.getOrNull()
        if (native != null) {
            return native
        }

        val blocks = (length + 31) / 32
        val out = ByteArray(blocks * 32)
        for (block in 1..blocks) {
            val index = byteArrayOf(
                (block ushr 24).toByte(), (block ushr 16).toByte(), (block ushr 8).toByte(), block.toByte(),
            )
            var u = hmacSha256(password, salt + index)
            val t = u.copyOf()
            for (round in 2..iterations) {
                u = hmacSha256(password, u)
                for (i in t.indices) {
                    t[i] = (t[i].toInt() xor u[i].toInt()).toByte()
                }
            }
            t.copyInto(out, (block - 1) * 32)
        }
        return out.copyOf(length)
    }

    fun generateEcdhKeyPair(): EcdhKeyPair {
        val pair = algorithm(ECDH).keyPairGenerator(EC.Curve.P256).generateKeyBlocking()
        return EcdhKeyPair(
            privateKey = EcdhPrivateKey(pair.privateKey),
            publicKeySpki = pair.publicKey.encodeToByteArrayBlocking(EC.PublicKey.Format.DER),
        )
    }

    /** Restores a key pair from its PKCS#8 private half. Only the conformance vectors need this. */
    fun ecdhPrivateKeyFromPkcs8(pkcs8: ByteArray): EcdhPrivateKey =
        EcdhPrivateKey(
            algorithm(ECDH)
                .privateKeyDecoder(EC.Curve.P256)
                .decodeFromByteArrayBlocking(EC.PrivateKey.Format.DER, pkcs8),
        )

    /**
     * ECDH P-256 agreement returning the **raw x coordinate**, 32 bytes, NOT hashed.
     *
     * Most protocols hash the shared secret; this one does not (`EphemeralKey.DeriveRawSecret` on the C#
     * side). Getting it wrong would surface three messages later as a tag mismatch with no clue why, which
     * is exactly why there is a vector for it.
     */
    fun ecdhRawSecret(privateKey: EcdhPrivateKey, peerSpki: ByteArray): ByteArray {
        val peer = algorithm(ECDH)
            .publicKeyDecoder(EC.Curve.P256)
            .decodeFromByteArrayBlocking(EC.PublicKey.Format.DER, peerSpki)
        return privateKey.key.sharedSecretGenerator().generateSharedSecretBlocking(peer).toByteArray()
    }

    /**
     * A new ECDSA P-256 signing key: this installation's identity.
     *
     * The controller had no private key of its own until accounts existed — it only ever verified a host's.
     * Linking to an account needs one, and this is the same shape the desktop has used since the beginning
     * (`IdentityKey.Create`), so one implementation of the challenge works for both.
     */
    fun generateEcdsaKeyPair(): EcdsaKeyPair {
        val pair = algorithm(ECDSA).keyPairGenerator(EC.Curve.P256).generateKeyBlocking()
        return EcdsaKeyPair(
            privateKeyPkcs8 = pair.privateKey.encodeToByteArrayBlocking(EC.PrivateKey.Format.DER),
            publicKeySpki = pair.publicKey.encodeToByteArrayBlocking(EC.PublicKey.Format.DER),
        )
    }

    /**
     * Signs with a stored PKCS#8 private key, producing 64-byte r‖s.
     *
     * RAW rather than DER for the same reason [ecdsaVerify] reads RAW: the C# side is
     * `DSASignatureFormat.IeeeP1363FixedFieldConcatenation`, and a DER signature is silently rejected by it.
     */
    fun ecdsaSign(privateKeyPkcs8: ByteArray, data: ByteArray): ByteArray =
        algorithm(ECDSA)
            .privateKeyDecoder(EC.Curve.P256)
            .decodeFromByteArrayBlocking(EC.PrivateKey.Format.DER, privateKeyPkcs8)
            .signatureGenerator(SHA256, ECDSA.SignatureFormat.RAW)
            .generateSignatureBlocking(data)

    /**
     * Verifies an ECDSA P-256 signature over SHA-256, with the signature as 64-byte r‖s and the public key
     * as SPKI DER. RAW, not DER: the host emits P1363 and a verifier expecting DER rejects every signature.
     */
    fun ecdsaVerify(publicKeySpki: ByteArray, data: ByteArray, signature: ByteArray): Boolean {
        if (signature.size != SIGNATURE_BYTES) {
            return false
        }

        return try {
            algorithm(ECDSA)
                .publicKeyDecoder(EC.Curve.P256)
                .decodeFromByteArrayBlocking(EC.PublicKey.Format.DER, publicKeySpki)
                .signatureVerifier(SHA256, ECDSA.SignatureFormat.RAW)
                .tryVerifySignatureBlocking(data, signature)
        } catch (e: Throwable) {
            // A malformed key is a failed verification, not a crash: the bytes came from the network.
            false
        }
    }

    /**
     * AES-256-GCM. Returns ciphertext followed by the 16-byte tag.
     *
     * Supplying the nonce is a delicate API because reusing one under a key destroys GCM entirely. That is
     * exactly why the protocol specifies it: a 4-byte prefix from the handshake and a counter that starts at
     * 1 and never repeats, so both ends agree on it without ever putting it on the wire. Letting the library
     * choose a random IV instead would be unusable — the other end would have no idea what it was.
     */
    @OptIn(DelicateCryptographyApi::class)
    fun aesGcmSeal(key: ByteArray, nonce: ByteArray, plaintext: ByteArray, associatedData: ByteArray): ByteArray =
        gcm(key).encryptWithIvBlocking(nonce, plaintext, associatedData)

    /** AES-256-GCM. Null when the tag does not verify — the caller must close the session, not carry on. */
    @OptIn(DelicateCryptographyApi::class)
    fun aesGcmOpen(key: ByteArray, nonce: ByteArray, ciphertextAndTag: ByteArray, associatedData: ByteArray): ByteArray? =
        try {
            gcm(key).decryptWithIvBlocking(nonce, ciphertextAndTag, associatedData)
        } catch (e: Throwable) {
            null
        }

    private fun gcm(key: ByteArray) =
        algorithm(AES.GCM)
            .keyDecoder()
            .decodeFromByteArrayBlocking(AES.Key.Format.RAW, key)
            .cipher()

    const val SIGNATURE_BYTES = 64
}

/**
 * Which backends this platform uses, in preference order. Declared rather than discovered: see the note on
 * [Crypto] about why an implicit default fails on a device and not in a test.
 */
internal expect fun cryptographyProviders(): List<CryptographyProvider>

/** Secure random bytes. The one thing the crypto library does not provide, so the one thing per platform. */
internal expect fun secureRandomBytes(count: Int): ByteArray

/** A platform cannot do something the protocol requires. Never caught in order to carry on regardless. */
internal class CryptoUnavailableException(message: String) : Exception(message)

/** An opaque private key; the private half never becomes bytes unless something asks for PKCS#8. */
internal class EcdhPrivateKey(internal val key: ECDH.PrivateKey)

/** A session's ephemeral key: the private half stays opaque, the public half goes on the wire as SPKI DER. */
internal class EcdhKeyPair(val privateKey: EcdhPrivateKey, val publicKeySpki: ByteArray)
