package com.sunllo.deskpair.media

/**
 * GF(2^8) with the 0x11D polynomial, the field the desktop's encoder works in.
 *
 * Arithmetic here is not analogous to the C# side, it is the same arithmetic: the tables are built the same
 * way from the same polynomial, so a coefficient computed here equals the one computed there. There is no
 * vectorised path — the phone only ever decodes, and only when a shard is actually lost, so the scalar loop
 * runs rarely and on a few kilobytes.
 */
internal object GaloisField {

    private const val POLYNOMIAL = 0x11D

    private val exp = ByteArray(512)
    private val log = ByteArray(256)

    init {
        var x = 1
        for (i in 0 until 255) {
            exp[i] = x.toByte()
            log[x] = i.toByte()
            x = x shl 1
            if (x >= 256) {
                x = x xor POLYNOMIAL
            }
        }
        for (i in 255 until 512) {
            exp[i] = exp[i - 255]
        }
    }

    fun multiply(a: Int, b: Int): Int =
        if (a == 0 || b == 0) 0 else exp[logOf(a) + logOf(b)].toInt() and 0xFF

    fun inverse(a: Int): Int {
        require(a != 0) { "GF(256) has no inverse of 0." }
        return exp[255 - logOf(a)].toInt() and 0xFF
    }

    /** destination[i] ^= coefficient * source[i], which is every operation this code does. */
    fun multiplyAdd(destination: ByteArray, source: ByteArray, coefficient: Int, length: Int) {
        if (coefficient == 0) {
            return
        }

        if (coefficient == 1) {
            for (i in 0 until length) {
                destination[i] = (destination[i].toInt() xor source[i].toInt()).toByte()
            }
            return
        }

        val logC = logOf(coefficient)
        for (i in 0 until length) {
            val v = source[i].toInt() and 0xFF
            if (v != 0) {
                destination[i] = (destination[i].toInt() xor exp[logOf(v) + logC].toInt()).toByte()
            }
        }
    }

    private fun logOf(value: Int): Int = log[value and 0xFF].toInt() and 0xFF
}

/**
 * Systematic Reed-Solomon erasure coding over GF(256) with a Cauchy generator: k data shards produce m
 * parity shards, and any k of the k + m recover the data.
 *
 * Only the decoding half is here. The phone never builds parity — that is the sender's job — and leaving
 * the encoder out is not laziness but the point: the code that runs on a phone should be the code a phone
 * needs, and half as much of it can go wrong.
 *
 * This is the fiddliest arithmetic in the client, and it fails in the worst way: a decode that is subtly
 * wrong produces a shard of plausible bytes, which becomes a frame the decoder accepts and draws as
 * garbage. So it is checked against recovery cases generated by the desktop's own encoder rather than
 * against itself.
 */
internal object ReedSolomon {

    const val MAX_SHARDS = 255

    /** The generator coefficient for parity row [row] and data column [column]. */
    fun coefficient(k: Int, row: Int, column: Int): Int = GaloisField.inverse((k + row) xor column)

    /**
     * Fills in the missing data shards in place.
     *
     * [shards] holds k data buffers followed by m parity buffers, all the same length; [present] says which
     * arrived. Missing entries must already be allocated, because they are written into. Returns false when
     * fewer than k shards are present, which is not an error — it is the frame being unrecoverable, and the
     * caller asks for a keyframe instead.
     */
    fun decode(shards: Array<ByteArray>, present: BooleanArray, k: Int, shardLength: Int): Boolean {
        val total = shards.size
        val m = total - k
        require(k > 0 && m >= 0 && present.size == total) { "Inconsistent shard layout." }

        var available = 0
        for (i in 0 until total) {
            if (present[i]) available++
        }

        var anyMissingData = false
        for (i in 0 until k) {
            if (!present[i]) anyMissingData = true
        }

        if (!anyMissingData) {
            return true
        }
        if (available < k) {
            return false
        }

        // Any k present shards will do. A data row is an identity row of the generator matrix; a parity
        // row is one of its Cauchy rows.
        val rows = IntArray(k)
        var n = 0
        var i = 0
        while (i < total && n < k) {
            if (present[i]) {
                rows[n++] = i
            }
            i++
        }

        val matrix = Array(k) { IntArray(k) }
        for (r in 0 until k) {
            val source = rows[r]
            if (source < k) {
                matrix[r][source] = 1
            } else {
                for (c in 0 until k) {
                    matrix[r][c] = coefficient(k, source - k, c)
                }
            }
        }

        val inverse = invert(matrix, k)

        // data_j = sum over r of inverse[j][r] * shard[rows[r]]
        for (j in 0 until k) {
            if (present[j]) {
                continue
            }

            shards[j].fill(0, 0, shardLength)
            for (r in 0 until k) {
                GaloisField.multiplyAdd(shards[j], shards[rows[r]], inverse[j][r], shardLength)
            }
        }

        return true
    }

    /** Gauss-Jordan over GF(256). The matrix is Cauchy, so a singular one means a shard layout that lied. */
    private fun invert(a: Array<IntArray>, n: Int): Array<IntArray> {
        val work = Array(n) { IntArray(2 * n) }
        for (r in 0 until n) {
            for (c in 0 until n) {
                work[r][c] = a[r][c]
            }
            work[r][n + r] = 1
        }

        for (col in 0 until n) {
            var pivot = -1
            for (r in col until n) {
                if (work[r][col] != 0) {
                    pivot = r
                    break
                }
            }
            check(pivot >= 0) { "Singular decoding matrix." }

            if (pivot != col) {
                val swap = work[col]
                work[col] = work[pivot]
                work[pivot] = swap
            }

            val inv = GaloisField.inverse(work[col][col])
            for (c in 0 until 2 * n) {
                work[col][c] = GaloisField.multiply(work[col][c], inv)
            }

            for (r in 0 until n) {
                if (r == col || work[r][col] == 0) {
                    continue
                }
                val factor = work[r][col]
                for (c in 0 until 2 * n) {
                    work[r][c] = work[r][c] xor GaloisField.multiply(factor, work[col][c])
                }
            }
        }

        return Array(n) { r -> IntArray(n) { c -> work[r][n + c] } }
    }
}
