using System.Globalization;
using Avalonia.Markup.Xaml;

namespace DeskPair.Desktop.Localization;

/// <summary>
/// UI strings. English is the source and the fallback; every other language is a table of the same keys in
/// <c>Translations/</c>, one file per language, registered in <see cref="AppLanguages"/>. The language
/// follows the OS unless overridden in settings, and is a static because a desktop has one user.
///
/// It used to be one table of (English, Chinese) pairs, which is the right shape for two languages and the
/// wrong one for ten -- the website went through the same change first (<c>PortalStrings</c>).
/// </summary>
public static class Strings
{
    private static readonly Dictionary<string, string> Table = new(StringComparer.Ordinal)
    {
        ["app.title"] = "DeskPair",
        ["home.tab"] = "Home",
        ["settings.tab"] = "Settings",
        ["home.yourDesk"] = "Your desk",
        ["home.id"] = "ID",
        ["home.password"] = "One-time password",
        ["home.copy"] = "Copy",
        ["home.refreshPassword"] = "New password",
        ["home.serviceOffline"] = "Host service not running",
        ["home.serverRegistered"] = "Reachable by id",
        ["home.serverConnecting"] = "Connecting to the signalling server…",
        ["home.serverUnreachable"] = "The signalling server is not answering — no network? This computer registers again by itself when it is back.",
        ["home.connecting"] = "Connecting to host service…",
        ["home.showQr"] = "Show the code for the phone app",
        ["home.qrTitle"] = "Scan this with DeskPair on your phone",
        ["home.qrHint"] = "It fills in this computer's ID and the server settings in one go.",
        // It used to say the code held no password, which was true and is no longer. The code now
        // carries a one-time password of its own, and what somebody needs to know is that it stops
        // working the moment it has been used -- and that until then the picture is the key.
        ["home.qrOneTime"] = "It carries a one-time password, which stops working as soon as somebody connects with it.",
        ["home.controlRemote"] = "Control a remote desk",
        ["home.remoteId"] = "Remote ID or address",
        ["home.connect"] = "Connect",
        ["home.fileTransfer"] = "File transfer",
        ["home.recent"] = "Recent",
        ["home.noRecent"] = "No recent connections",
        ["home.permanentPassword"] = "Permanent password",
        ["home.setPassword"] = "Set",
        ["home.passwordSet"] = "Permanent password updated",
        ["signIn.title"] = "DeskPair account",
        ["signIn.signIn"] = "Sign in",
        ["signIn.register"] = "Create an account",
        ["signIn.email"] = "Email address",
        ["signIn.password"] = "Password",
        ["signIn.forgot"] = "Forgotten your password? Reset it on the portal's website.",
        ["settings.portalHint"] = "Empty uses the official portal",
        // ---- what the portal refuses, by the code it sends rather than the sentence ----
        // The sentence stays as the fallback in PortalMessage, so a code added on the server later still
        // says something true here instead of nothing.
        ["portal.unreachable"] = "Could not reach the portal at {0}.",
        ["portal.timeout"] = "The portal at {0} did not answer in time.",
        ["portal.empty"] = "The portal sent an empty answer.",
        ["portal.http"] = "The portal answered with an error.",
        ["portal.bad_credentials"] = "That email address and password do not match.",
        ["portal.not_verified"] = "Confirm your email address first; check your inbox.",
        ["portal.disabled"] = "That account has been turned off.",
        ["portal.closed"] = "This portal does not take new accounts.",
        ["portal.email_taken"] = "That address already has an account. Sign in instead.",
        ["portal.weak_password"] = "That password is too short.",
        ["portal.bad_email"] = "That does not look like an email address.",
        ["portal.too_many"] = "Too many attempts. Wait a few minutes and try again.",
        ["portal.refused"] = "That did not work.",
        ["portal.unlinked"] = "This computer is not linked to an account.",
        ["portal.bad_code"] = "The portal would not accept this sign-in. Try again.",
        ["portal.bad_signature"] = "This computer could not prove it owns its key.",
        ["portal.bad_key"] = "This computer's key was refused.",
        ["settings.account.intro"] = "Link this computer to a DeskPair account to keep your saved computers in step across your devices.",
        ["settings.account.portal"] = "Portal address",
        ["settings.account.nameFromGeneral"] = "This computer is listed under the name set on the General tab.",
        ["settings.account.link"] = "Link",
        ["settings.account.unlink"] = "Unlink this computer",
        ["settings.account.needBoth"] = "Enter your email address and password.",
        ["settings.account.checkEmail"] = "Account created. Open the link in the email we sent, then sign in here.",
        ["settings.account.linkedAs"] = "Linked to {0} as “{1}”",
        ["settings.account.unlinked"] = "This computer is no longer linked.",
        ["settings.account.unlinkedLocally"] = "Unlinked here, but the portal was not told ({0}). Revoke it from the portal as well.",
        ["settings.account.timedOut"] = "The portal did not answer in time.",
        ["settings.server"] = "Rendezvous server",
        ["settings.serverKey"] = "Server public key",
        ["settings.fetchKey"] = "Fetch from server",
        ["settings.selfHosted"] = "I run my own servers",
        ["settings.directoryHint"] = "DeskPair asks the portal which signalling server to use, so nothing here needs filling in.",
        ["settings.keyFetched"] = "Public key fetched and pinned; fingerprint {0}. Compare it with the server's start-up log if in doubt.",
        ["settings.keyFetchFailed"] = "Could not fetch the key: {0}",
        ["settings.keyInvalid"] = "The public key is not valid base64; use \"Fetch from server\"",
        ["settings.serverRequired"] = "Enter the rendezvous server first",
        ["session.keyMissing"] = "No server public key configured; fetching it from {0}",
        ["session.keyPinned"] = "Pinned the server key (fingerprint {0}) for {1}",
        ["settings.approveMode"] = "Verification method",
        ["settings.approve.password"] = "Password",
        ["settings.approve.click"] = "Ask me",
        ["settings.approve.both"] = "Password or ask me",
        ["settings.permissions"] = "Permissions granted to controllers",
        ["settings.keyboard"] = "Keyboard and mouse",
        ["settings.clipboard"] = "Clipboard",
        ["settings.audio"] = "Audio",
        ["settings.files"] = "File transfer",
        ["settings.directAccess"] = "Accept direct connections on port",
        ["settings.language"] = "Language",
        ["settings.language.system"] = "System",
        ["settings.save"] = "Save",
        ["settings.saved"] = "Settings saved",
        ["settings.hostSection"] = "This computer (host)",
        ["settings.controllerSection"] = "Connecting to others (controller)",
        ["session.connecting"] = "Connecting…",
        ["session.password"] = "Password",
        ["session.login"] = "Log in",
        ["session.cancel"] = "Cancel",
        ["session.waitingApproval"] = "Waiting for the remote user to accept…",
        ["session.closed"] = "Connection closed",
        ["session.display"] = "Display",
        ["session.quality"] = "Quality",
        ["session.resolution"] = "Resolution",
        ["session.resolution.original"] = "Original",
        ["session.resolution.failed"] = "The resolution could not be changed: {0}",
        ["session.openDisplayWindow"] = "Show another display in a window of its own",
        ["session.addDisplay"] = "Add a display the remote computer does not have",
        ["session.addedDisplay"] = "added",
        ["session.removeDisplay"] = "Remove this display",
        ["session.addDisplay.failed"] = "A display could not be added: {0}",
        ["session.removeDisplay.failed"] = "The display could not be removed: {0}",
        ["screen.title"] = "{0} · Display {1}",
        ["screen.refresh"] = "Ask for a fresh picture of this display",
        ["screen.showSession"] = "Show session",
        ["screen.failed"] = "That display could not be shown: {0}",
        ["screen.gone"] = "A display of {0} is no longer there; its window has closed.",
        ["session.quality.low"] = "Low",
        ["session.quality.balanced"] = "Balanced",
        ["session.quality.best"] = "Best",
        ["session.frameRate.auto"] = "Auto",
        ["session.frameRate.tip"] = "The most frames a second the remote computer sends. With Auto it chooses; on a slow connection it sends fewer than any of these.",
        ["session.keyboardMode"] = "Keyboard",
        ["session.keyboard.map"] = "Positional",
        ["session.keyboard.translate"] = "Translate",
        ["session.ctrlAltDel"] = "Ctrl+Alt+Del",
        ["session.lock"] = "Lock",
        ["session.chat"] = "Chat",
        ["session.files"] = "Files",
        ["session.audio"] = "Audio",
        ["session.fit"] = "Fit",
        ["session.original"] = "1:1",
        ["session.fullscreen"] = "Full screen",
        ["session.closeTab"] = "Close this session",
        ["session.remoteCursor"] = "Show the remote pointer as well as yours",
        ["session.stalled"] = "Connection lost — waiting",
        ["session.stalledHint"] = "The picture is the last one that arrived",
        ["session.noDisplays"] = "This computer has no screen",
        ["session.noDisplaysHint"] = "Nothing is shown here; file transfer and chat still work",
        ["session.disconnect"] = "Disconnect",
        ["session.rtt"] = "RTT",
        ["session.stream.video"] = "video",
        ["session.stream.tiles"] = "lossless",
        ["session.retryAfter"] = "Too many attempts; try again in {0} s",
        ["chat.send"] = "Send",
        ["chat.placeholder"] = "Type a message",
        ["cm.title"] = "Connection manager",
        ["cm.incoming"] = "Incoming connection",
        ["cm.accept"] = "Accept",
        ["cm.reject"] = "Reject",
        ["cm.wantsToControl"] = "{0} ({1}) wants to control this computer",
        ["cm.wantsFiles"] = "{0} ({1}) wants to transfer files",
        ["cm.close"] = "Close connection",
        ["cm.disconnect"] = "Disconnect",
        ["cm.deviceId"] = "Device ID: ",
        ["cm.allowAccess"] = "Allowed access:",
        ["cm.perm.audio"] = "🔊 Audio",
        ["cm.perm.input"] = "⌨ Keyboard & mouse",
        ["cm.perm.files"] = "📁 Files",
        ["cm.perm.clipboard"] = "📋 Clipboard",
        ["cm.noConnections"] = "No active connections",
        ["cm.transfers"] = "File transfers",
        ["files.local"] = "Local",
        ["files.remote"] = "Remote",
        ["files.up"] = "Up",
        ["files.refresh"] = "Refresh",
        ["files.send"] = "Send →",
        ["files.receive"] = "← Receive",
        ["files.newFolder"] = "New folder",
        ["files.delete"] = "Delete",
        ["files.jobs"] = "Transfers",
        ["files.cancelJob"] = "Cancel",
        ["files.name"] = "Name",
        ["files.size"] = "Size",
        ["files.modified"] = "Modified",
        ["tray.show"] = "Open DeskPair",
        ["tray.settings"] = "Settings",
        ["tray.signOut"] = "Sign out",
        ["tray.signOutSoon"] = "Accounts are not available yet",
        ["tray.quit"] = "Quit",
        // ---- navigation and the settings screen ----
        ["nav.remote"] = "Remote control",
        ["nav.settings"] = "Settings",
        ["nav.account.signIn"] = "Not signed in",
        ["settings.tab.general"] = "General",
        ["settings.tab.display"] = "Display",
        ["settings.tab.input"] = "Keyboard and mouse",
        ["settings.tab.security"] = "Security",
        ["settings.tab.network"] = "Network",
        ["settings.hostOffline"] = "The host service is not running; settings for this computer are disabled",
        ["settings.restartRequired"] = "Saved. Some changes take effect after the host service restarts",
        ["settings.saveFailed"] = "Could not save: {0}",
        ["settings.thisComputer"] = "This computer",
        ["settings.whenConnecting"] = "When connecting to others",
        // general
        ["settings.deviceName"] = "Name shown to visitors",
        ["settings.deviceNameHint"] = "Empty uses the computer name",
        ["settings.deviceNameWhere"] = "Shown to anyone connecting here, and in your account's device list.",
        ["settings.startWithSystem"] = "Start when I sign in",
        ["settings.startWithSystemHint"] = "No service is installed, so this desk is reachable only after you sign in",
        ["settings.startMinimised"] = "Start minimised to the notification area",
        ["settings.closeToTray"] = "Closing the window keeps running in the notification area",
        ["settings.startupFailed"] = "Could not change the startup entry: {0}",
        ["settings.startupNeedsBundle"] = "DeskPair has to be in the Applications folder first",
        ["settings.startupLaunchctl"] = "launchctl would not load the login item",
        ["settings.languageRestart"] = "Saved. The new language applies to windows opened from now on",
        ["settings.fileFolder"] = "File transfer starts in",
        ["settings.fileFolderHint"] = "Empty uses your user folder",
        ["settings.recentLimit"] = "Recent connections to remember",
        ["settings.recentLimitInvalid"] = "Remember between 1 and 200 connections",
        ["settings.versionValue"] = "Version {0}",
        ["settings.openLogs"] = "Open the log folder",

        // software updates
        ["settings.updates"] = "Updates",
        ["settings.checkForUpdates"] = "Check for new versions",
        ["settings.checkForUpdatesHint"] = "DeskPair asks the portal what the newest version is. It never downloads or installs anything by itself.",
        ["settings.checkNow"] = "Check now",
        ["settings.checking"] = "Checking\u2026",
        ["settings.upToDate"] = "This is the newest version.",
        ["settings.updateAvailable"] = "Version {0} is available.",
        ["settings.updateNotes"] = "What's new",
        ["settings.lastChecked"] = "Last checked {0}",
        ["settings.neverChecked"] = "Not checked yet",
        ["settings.updateCheckFailed"] = "Could not check for updates: {0}",
        ["settings.openDownloadPage"] = "Open the download page",
        ["settings.openFailed"] = "Could not open {0}",

        // the notice on the main window
        ["update.available"] = "DeskPair {0} is available \u2014 this computer has {1}",
        ["update.get"] = "Get the update",
        ["update.install"] = "Install and restart",
        ["update.signed"] = "Signed by the DeskPair release key. The download is installed only if its hash matches the signed manifest; DeskPair then restarts.",
        ["update.downloading"] = "Downloading… {0}%",
        ["update.verifying"] = "Verifying the download…",
        ["update.installing"] = "Installing…",
        ["update.restarting"] = "Installed. DeskPair is restarting.",
        ["update.failed"] = "The update was not installed: {0}",
        ["update.dismiss"] = "Not now",
        ["update.manual"] = "The download page opens in your browser. DeskPair does not install it for you.",
        // display
        ["settings.defaultQuality"] = "Picture quality for new sessions",
        ["settings.quality.custom"] = "Custom",
        ["settings.bitrate"] = "Bitrate (kbps)",
        ["settings.bitrateInvalid"] = "Use a bitrate between 100 and 200000 kbps",
        ["settings.fps"] = "Frame rate",
        ["settings.fpsInvalid"] = "Use a frame rate between 5 and 120",
        ["settings.showCursor"] = "Show the remote mouse pointer",
        ["settings.lossless"] = "Sharpen to pixel-perfect once the picture settles",
        ["settings.fitToWindow"] = "Scale the remote screen to the window",
        ["settings.smoothPlayback"] = "Smooth playback (adds a little delay)",
        ["settings.codec"] = "Video encoder on this computer",
        ["settings.codec.auto"] = "Automatic",
        ["settings.allowVirtualDisplay"] = "Let viewers add displays this computer does not have",
        ["settings.allowVirtualDisplayHint"] = "For a viewer with keyboard and mouse control who wants a second screen. Added displays disappear when the last viewer disconnects.",
        ["settings.displayDriver.missing"] = "The virtual display driver is not installed.",
        ["settings.displayDriver.needsService"] = "The virtual display driver is installed. Displays can be added once “{0}” is on in Settings › {1}.",
        ["settings.displayDriver.ready"] = "The virtual display driver is installed; viewers can add displays.",
        ["settings.displayDriver.install"] = "Install the virtual display driver",
        ["settings.displayDriver.remove"] = "Remove the virtual display driver",
        ["settings.displayDriver.requested"] = "Approve the Windows prompt to continue",
        ["settings.displayDriver.failed"] = "That did not work; the reason is in service.log",
        ["settings.displayDriver.cancelled"] = "Cancelled; nothing was changed",
        // input
        ["settings.keyboardMode"] = "Keyboard",
        ["settings.keyboardTranslateHint"] = "Translate characters instead of key positions; use it when the two keyboard layouts differ",
        ["settings.lockAfterEnd"] = "Lock the remote computer when I disconnect",
        ["settings.allowKeyboard"] = "Visitors may use the keyboard and mouse",
        ["settings.allowClipboard"] = "Visitors may share the clipboard",
        ["settings.allowRestart"] = "Visitors may restart this computer",
        ["settings.allowTerminal"] = "Terminal",
        // security
        ["settings.approvalTimeout"] = "Seconds to wait for approval",
        ["settings.approvalTimeoutInvalid"] = "Wait between 5 and 300 seconds",
        ["settings.allowPasswordInClick"] = "A correct password connects without asking me",
        ["settings.tempPassword"] = "One-time password",
        ["settings.tempPasswordEnabled"] = "Allow the one-time password",
        ["settings.tempPasswordLength"] = "Length",
        ["settings.rotation"] = "Change it once wrong guesses have come from this many addresses",
        ["settings.rotationInvalid"] = "Use between 1 and 100 attempts",
        ["settings.rotateAfterSession"] = "Change it after every session",
        ["settings.permanentSet"] = "A permanent password is set",
        ["settings.permanentNotSet"] = "No permanent password",
        ["settings.clearPassword"] = "Clear",
        ["settings.passwordCleared"] = "Permanent password cleared",
        ["settings.passwordFailed"] = "Could not set the password",
        ["settings.passwordTooShort"] = "Use at least {0} characters",
        ["settings.allowAudio"] = "Visitors may hear this computer",
        ["settings.allowFiles"] = "Visitors may transfer files",
        ["settings.knownHosts"] = "Computers trusted on first connection",
        ["settings.knownHostsHint"] = "Forget one to be asked again the next time its key changes",
        ["settings.forget"] = "Forget",
        ["settings.forgetAll"] = "Forget all",
        ["settings.allowlist"] = "Who may connect",
        ["settings.allowlistEnabled"] = "Only accept connections from the addresses below",
        ["settings.allowlistHint"] = "Everyone else is refused before they are even asked for a password. The password still applies to those who are on the list.",
        ["settings.allowlistEmpty"] = "The list is empty, so nobody can connect to this computer.",
        ["settings.allowlistPlaceholder"] = "203.0.113.5, 192.168.1.0/24 or id:123456789",
        ["settings.allowlistBadEntry"] = "That is not an address, a range or an id.",
        ["settings.allowlistNoRelay"] = "Refuse connections that come through a relay server",
        ["settings.allowlistNoRelayHint"] = "A relayed connection arrives from the relay, so the address on the list is checked against what the signalling server reports rather than what this computer can see. Refusing them trusts only what the connection itself shows, but someone whose network cannot be reached directly will not get in at all.",
        ["settings.add"] = "Add",
        ["settings.remove"] = "Remove",
        ["settings.noKnownHosts"] = "Nothing trusted yet",
        // network
        ["settings.directPort"] = "Port",
        ["settings.portInvalid"] = "Use a port between 1 and 65535",
        ["settings.udpMedia"] = "Send video over UDP with error correction",
        ["settings.udpMediaViewer"] = "Accept video over UDP",
        ["settings.forceRelay"] = "Always connect through a relay",
        ["settings.forceRelayHost"] = "Answer incoming connections through a relay",
        // home
        ["home.copied"] = "Copied",
        ["home.passwordDisabled"] = "Disabled",
        ["home.passwordRegenerated"] = "New one-time password generated",
        ["home.passwordPinned"] = "Chosen by you",
        ["home.show"] = "Show",
        ["home.hide"] = "Hide",
        ["home.addToDevices"] = "Save to devices",
        ["home.addedToDevices"] = "Added to the device list",
        ["home.alreadyInDevices"] = "Already in the device list",
        ["home.remoteDesk"] = "Computer to control",
        ["home.thisDesk"] = "This computer",
        ["home.tempPasswordHint"] = "Give the ID and this password to whoever should connect",
        // settings: page headings
        ["settings.tab.audio"] = "Sound",
        ["settings.tab.about"] = "About DeskPair",
        ["settings.generalIntro"] = "Language, start-up and where files are kept.",
        ["settings.displayIntro"] = "Picture quality for new sessions, and how this computer encodes video.",
        ["settings.audioIntro"] = "Sound sent out from this computer, and sound played back from the other side.",
        ["settings.inputIntro"] = "How keys are sent, and what visitors may use on this desk.",
        ["settings.securityIntro"] = "Who may connect to this computer, and how they prove it.",
        ["settings.networkIntro"] = "Servers, ports and how video travels.",
        ["settings.aboutIntro"] = "What this build is and where it keeps its files.",
        ["settings.savedLive"] = "Saved",
        ["settings.rangeInvalid"] = "Use a number between {0} and {1}",
        // settings: sound
        ["settings.audioSend"] = "Sound sent to the other side",
        ["settings.audioPlay"] = "Playing sound from the other side",
        ["settings.audioOff"] = "Disabled",
        ["settings.audioSendDevice"] = "Send what plays on the selected device",
        ["settings.audioStandardDevice"] = "Use the standard device",
        ["settings.audioChooseDevice"] = "Use the selected device",
        ["settings.audioExclusive"] = "Play exclusively on this device",
        ["settings.audioExclusiveHint"] = "Lower delay, but other programs cannot use the device while a session runs",
        ["settings.audioNoDevices"] = "No sound devices were found on this computer",
        ["settings.audioDeviceHint"] = "Changes apply to the next session",
        // settings: recording
        ["settings.recording"] = "Recording",
        ["settings.recordingFolder"] = "Recordings are saved in",
        ["settings.recordingFolderHint"] = "Empty uses Videos\\Sunllo DeskPair",
        ["settings.recordAudio"] = "Record sound as well as the picture",
        // settings: local network and firewall
        ["settings.lanAccess"] = "Accept connections from the local network, with no server in between",
        ["settings.lanAccessHint"] = "The other side connects to this computer's IP address. Works with no internet connection at all.",
        ["settings.firewallButton"] = "Allow through Windows Firewall",
        ["settings.firewallHint"] = "Creates the firewall rules once, as administrator, so Windows stops asking at every start.",
        ["session.noServer"] = "No signalling server: none is configured and the directory did not name one. Set one in Settings, or connect by address.",
        ["settings.unattended"] = "Reachable while locked",
        ["settings.unattendedHint"] = "Sets this computer up to be shown and controlled while it is locked or nobody is signed in. It needs a permanent password, because the temporary one is read off a screen that is not being shown.",
        ["settings.unattendedMacHint"] = "DeskPair must also be ticked in System Settings › Privacy & Security › Screen & System Audio Recording. Add it with the + button: once it is running at the login window it cannot ask for that itself, and without it the screen comes through empty.",
        ["mac.authorizeInstall"] = "DeskPair is setting this Mac up to be reached while it is locked or signed out.",
        ["mac.authorizeRemove"] = "DeskPair is removing the background job that let this Mac be reached while it was locked or signed out.",
        ["settings.unattendedMacPrompt"] = "macOS will ask for your password next, for DeskPair.",
        ["settings.unattendedLinuxHint"] = "This installs a small root service (sunllo-deskpair) that reads the screen and provides a virtual keyboard and mouse, and a 'deskpair' account that the engine itself runs as. Your system will ask for your password.",
        ["settings.unattendedNoPrompt"] = "Nothing here can ask for administrator rights. In a terminal, run: {0}",
        ["settings.unattendedEnable"] = "Turn on",
        ["settings.unattendedDisable"] = "Turn off",
        ["settings.unattendedOnNow"] = "On",
        ["settings.unattendedOffNow"] = "Off",
        ["settings.unattendedOn"] = "This computer can now be reached while it is locked.",
        ["settings.unattendedOff"] = "This computer can no longer be reached while it is locked.",
        ["settings.unattendedOnFailed"] = "Could not turn it on. Check that a permanent password is set.",
        ["settings.unattendedOffFailed"] = "Could not turn it off.",
        ["settings.unattendedCancelled"] = "Nothing changed: the administrator prompt was declined.",
        ["settings.firewallRequested"] = "Firewall rules requested; approve the Windows prompt",
        ["settings.firewallAdded"] = "Firewall rules added",
        ["settings.firewallFailed"] = "Could not add the firewall rules",
        ["settings.firewallCancelled"] = "Cancelled; the firewall rules were not changed",
        ["settings.directPortHint"] = "Turned on and off on the Security page",
        // settings: macOS permissions (this section only appears on macOS)
        ["settings.macPermissions"] = "macOS permissions",
        ["settings.macPermissionsHint"] = "macOS must be told to let DeskPair see the screen and control the keyboard and mouse. Grant these in System Settings, then reopen DeskPair.",
        ["settings.macScreenRecording"] = "Screen Recording — lets others see this Mac's screen",
        ["settings.macAccessibility"] = "Accessibility — lets others control the keyboard and mouse",
        ["settings.macLocalNetwork"] = "Local Network — needed to find computers on the same network",
        ["settings.macGranted"] = "Granted",
        ["settings.macNotGranted"] = "Not granted",
        // macOS exposes no API to read the Local Network consent, so it can only be checked by eye.
        ["settings.macUnknown"] = "Check in System Settings",
        // macOS ships no anchor for the Local Network pane, so the button can only reach Privacy & Security.
        ["settings.macLocalNetworkHint"] = "macOS has no direct link to this one: open Privacy & Security and pick Local Network from the list.",
        ["settings.macOpenSettings"] = "Open System Settings",
        ["settings.macRecheck"] = "Check again",
        ["settings.macRestartHint"] = "A permission you just changed only takes effect after DeskPair is closed and reopened.",
        ["settings.waylandSharing"] = "Screen sharing on Wayland",
        ["settings.waylandSharingHint"] = "This desktop asks the person at this computer before anyone can see or control it. Allow it here once, and viewers are let in without the question.",
        ["settings.waylandSharingHintUnattended"] = "With “Reachable while locked” set up, people who connect see this computer's screen as the graphics hardware shows it: only the first display, and no pointer. Allow sharing through the desktop here once, and while it is unlocked they see every display and the pointer.",
        ["settings.waylandSharingRow"] = "Sharing this screen",
        ["settings.waylandSharingAllowed"] = "Allowed",
        ["settings.waylandSharingWatchOnlyState"] = "Watch only",
        ["settings.waylandSharingNotYet"] = "Not yet",
        ["settings.waylandSharingAllow"] = "Allow…",
        ["settings.waylandSharingDialog"] = "In the “Remote Desktop” dialog, turn on “Allow Remote Interaction”, keep “Remember This Selection” ticked and choose “Share”. Without the first, viewers can only watch; without the second, this computer asks again every time.",
        ["settings.waylandSharingAsking"] = "Answer the dialog on this screen…",
        ["settings.waylandSharingDone"] = "Allowed. Viewers now connect without the question.",
        ["settings.waylandSharingWatchOnly"] = "Allowed to watch only: “Allow Remote Interaction” was off. Allow again with it on to let viewers use the keyboard and mouse.",
        ["settings.waylandSharingDeclined"] = "Not allowed: the dialog was cancelled.",
        ["settings.waylandSharingUnanswered"] = "Not allowed: the dialog was not answered in time.",
        ["settings.waylandSharingFailed"] = "Screen sharing could not be set up: {0}",
        // settings: about
        ["settings.buildDate"] = "Built {0}",
        ["settings.logs"] = "Logs",
        ["settings.logsHint"] = "If something goes wrong, the file in this folder is the one worth sending.",
        ["settings.noServer"] = "No server configured",
        ["settings.components"] = "Bundled software: Avalonia (MIT); NAudio (MIT); Vortice.Windows (MIT). Video is encoded and decoded by this computer's own Media Foundation codecs.",
        // device list
        ["nav.devices"] = "Devices",
        ["nav.history"] = "History",
        ["history.title"] = "Who has connected to this computer",
        ["history.subtitle"] = "Kept on this computer. It records who was here and what they were allowed to do, never what they saw or typed.",
        ["history.empty"] = "Nothing recorded yet.",
        ["history.refresh"] = "Refresh",
        ["history.clear"] = "Clear the record",
        ["history.cleared"] = "The record was cleared",
        ["history.unknownPeer"] = "An unnamed computer",
        ["history.noEnd"] = "no record of it ending",
        ["history.relayedFrom"] = "{0}, reported by the signalling server",
        ["history.allowed"] = "Allowed: {0}",
        ["history.terminal"] = "Terminal: {0} shell(s) opened, running as {1}",
        ["history.terminalNone"] = "Terminal connection; no shell was opened",
        ["terminal.open"] = "Terminal",
        ["terminal.title"] = "Terminal",
        ["terminal.copy"] = "Copy",
        ["terminal.pasteMenu"] = "Paste",
        ["terminal.paste"] = "Paste",
        ["terminal.pasteConfirm"] = "Paste {0} lines into the shell? Each line runs as a command.",
        ["terminal.notAllowed"] = "This computer does not allow a terminal. Its owner can turn one on in Settings, under Security; a DeskPair older than this one has no terminal at all.",
        ["terminal.opening"] = "Opening a shell…",
        ["terminal.ended"] = "The shell ended (exit code {0}).",
        ["terminal.endedReason"] = "The shell ended: {0}",
        ["terminal.failed"] = "Could not open a shell: {0}",
        ["terminal.newShell"] = "Open a new shell",
        ["terminal.connectionLost"] = "The connection was lost, and the shell with it. A shell does not survive its connection.",
        ["settings.terminal"] = "Terminal",
        ["settings.terminalHint"] = "Lets a viewer open a command line on this computer and run anything in it. With unattended access installed it runs as SYSTEM on Windows and root on Linux: that is the whole machine.",
        ["settings.terminalOff"] = "The terminal is off.",
        ["settings.terminalOn"] = "The terminal is on.",
        ["settings.terminalTurnOn"] = "Turn on the terminal…",
        ["settings.terminalConfirmText"] = "Anyone who connects with this computer's password and is allowed a terminal can then run any command here, as the account shown below, including when nobody is at this computer. Every shell opened is kept in the connection record. Turn it on?",
        ["settings.terminalNeedsPassword"] = "Set a permanent password first. Unattended access is installed, so the terminal would be reachable when nobody is at this computer.",
        ["settings.terminalConfirm"] = "Turn it on",
        ["settings.terminalTurnOff"] = "Turn off the terminal",
        ["settings.terminalRunsAs"] = "Shells run as",
        ["settings.terminalRunsAsSystem"] = "The most this computer allows (SYSTEM on Windows, root on Linux)",
        ["settings.terminalRunsAsUser"] = "The signed-in user",
        ["cm.wantsTerminal"] = "{0} ({1}) wants a terminal on this computer",
        ["cm.allowTerminal"] = "Allow a terminal, running as {0}",
        ["cm.terminalHint"] = "A terminal can run any command on this computer. Tick this only for someone you trust with it.",
        ["history.seconds"] = "{0} sec",
        ["history.minutes"] = "{0} min",
        ["history.hours"] = "{0} h {1} min",
        ["history.unavailable"] = "The engine could not be asked for the record.",
        ["history.upload"] = "Also keep this record with my account",
        ["history.uploadHint"] = "Only while this computer is signed in to an account. The same facts go up as are shown here — who connected, when and what they were allowed to do — and they are kept for 90 days.",
        ["history.uploadNotSaved"] = "That setting could not be saved.",
        ["history.auth.temporary"] = "temporary password",
        ["history.auth.permanent"] = "permanent password",
        ["history.auth.approval"] = "accepted at this computer",
        ["history.auth.none"] = "no password",
        ["devices.signInRequired"] = "Sign in to keep a device list",
        ["devices.signInRequiredHint"] = "The list belongs to your account: it is kept on the server, folders and all, and follows you to your phone and to any other computer you sign in on. Settings has the sign-in.",
        ["devices.title"] = "Devices",
        ["devices.intro"] = "Computers you connect to often, grouped however you like.",
        ["devices.search"] = "Search",
        ["devices.add"] = "Add a device",
        ["devices.addFromRecent"] = "Add from recent connections",
        ["devices.target"] = "ID or address",
        ["devices.targetHint"] = "123 456 789, or 192.168.1.5",
        ["devices.alias"] = "Name",
        ["devices.aliasHint"] = "What you call this computer",
        ["devices.group"] = "Group",
        ["devices.groupHint"] = "Empty means Ungrouped",
        ["devices.note"] = "Note",
        ["devices.ungrouped"] = "Ungrouped",
        ["devices.addGroup"] = "New group",
        ["devices.renameGroup"] = "Rename group",
        ["devices.deleteGroup"] = "Remove group",
        ["devices.groupName"] = "Group name",
        ["devices.groupNameHint"] = "Taipei office, Customer A, Server room…",
        ["devices.groupRequired"] = "Enter a name for the group",
        ["devices.groupEmpty"] = "Nothing in this group yet",
        ["devices.editDevice"] = "Edit device",
        ["devices.collapse"] = "Fold away",
        ["devices.expand"] = "Open",
        ["devices.groupCount"] = "{0} device(s)",
        ["devices.dragHint"] = "Drag a device onto a group to move it there",
        ["devices.groupDeleteHint"] = "Removing a group keeps its devices; they move to Ungrouped",
        ["devices.save"] = "Save",
        ["devices.cancel"] = "Cancel",
        ["devices.edit"] = "Edit",
        ["devices.delete"] = "Remove",
        ["devices.connect"] = "Control",
        ["devices.files"] = "Files",
        ["devices.online"] = "Online",
        ["devices.offline"] = "Offline",
        ["devices.unknown"] = "Unknown",
        ["devices.empty"] = "No devices yet. Add one, or add a recent connection.",
        ["devices.noMatch"] = "Nothing matches that search",
        ["devices.targetRequired"] = "Enter an ID or an address",
        ["devices.duplicate"] = "That device is already in the list",
        ["devices.lastConnected"] = "Last connected {0}",
        ["devices.never"] = "Never connected",
        // incoming connection notice
        ["incoming.verifying"] = "Connection from {0} · verifying",
        ["incoming.unknown"] = "an unknown computer",
        ["incoming.connected"] = "{0} is connected",
        ["incoming.dismiss"] = "Dismiss",
        ["incoming.manage"] = "Manage",
        ["incoming.tray"] = "Someone is connecting to this computer",
        // connection manager
        ["cm.collapse"] = "Collapse",
        ["cm.expand"] = "Expand",
        // session recording
        ["session.record"] = "Record",
        ["session.recordStop"] = "Stop recording",
        ["session.recordStarted"] = "Recording",
        ["session.recordSaved"] = "Saved to {0}",
        ["session.recordFailed"] = "Recording stopped: {0}",
        ["session.recordOpen"] = "Open the folder",
        ["session.recordStarting"] = "Recording starts at the next key frame…",
        ["session.recordUnsupported"] = "Recording is not available on this computer",
        ["session.recordSize"] = "{0} · {1}",
        ["settings.applyFailed"] = "Could not do that: {0}",
        ["crash.title"] = "Sunllo DeskPair",
        ["crash.body"] = "Sunllo DeskPair stopped unexpectedly.\n\n{0}\n\nDetails: {1}",
        ["error.connectFailed"] = "Could not connect: {0}",
        ["error.loginFailed"] = "Login failed: {0}",
    };

    private static string _language = AppLanguages.Match(CultureInfo.CurrentUICulture.Name);
    private static IReadOnlyDictionary<string, string>? _current = AppLanguages.Table(_language);

    /// <summary>
    /// The language in use, as a code from <see cref="AppLanguages.All"/>. Setting a known code uses it;
    /// anything else ("system", the config's default) follows the operating system through
    /// <see cref="AppLanguages.Match"/>. Reading it back gives the resolved code, never "system".
    /// </summary>
    public static string Language
    {
        get => _language;
        set
        {
            _language = AppLanguages.IsKnown(value) ? value : AppLanguages.Match(CultureInfo.CurrentUICulture.Name);
            _current = AppLanguages.Table(_language);
        }
    }

    /// <summary>The string in the current language, else in English, else the key itself (visible, and naming what is missing).</summary>
    public static string Get(string key)
    {
        if (_current is not null && _current.TryGetValue(key, out string? translated) && translated.Length > 0)
        {
            return translated;
        }

        return Table.TryGetValue(key, out string? english) ? english : key;
    }

    /// <summary>The English table, for the tests that hold every translation to it.</summary>
    internal static IReadOnlyDictionary<string, string> All => Table;

    /// <summary>A language's table, or null when there is none (English, or a language not yet translated).</summary>
    internal static IReadOnlyDictionary<string, string>? Translation(string code) => AppLanguages.Table(code);

    /// <summary>
    /// Whether there is a string for this key.
    ///
    /// For callers that have something else to say when there is not. <see cref="Get"/> answers a missing
    /// key with the key itself, which is the right thing on a label -- it is visible and names what is
    /// missing -- and the wrong thing for a message that already has a readable English fallback.
    /// </summary>
    public static bool Has(string key) => Table.ContainsKey(key);

    public static string Format(string key, params object[] args) => string.Format(CultureInfo.CurrentCulture, Get(key), args);
}

/// <summary>XAML: <c>Text="{loc:Loc home.connect}"</c>.</summary>
public sealed class LocExtension : MarkupExtension
{
    public LocExtension(string key)
    {
        Key = key;
    }

    public string Key { get; }

    public override object ProvideValue(IServiceProvider serviceProvider) => Strings.Get(Key);
}
