// Emits the conformance vectors the Kotlin client is checked against.
//
// The whole point is that these come out of the shipping code, not out of a second reading of it. Every
// value below is produced by calling DeskPair.Protocol itself, so a change to the handshake that
// nobody mirrors in Kotlin turns into a failing test rather than a session that silently does not connect —
// or worse, one that connects with keys derived a different way.
//
// Inputs are fixed rather than random so the file is reproducible: regenerating it after an unrelated change
// produces a byte-identical file, and a diff therefore means something.
//
//   dotnet run --project tools/DeskPair.Tools.Vectors -- <output.json>

using System.Buffers.Binary;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using DeskPair.Protocol;
using DeskPair.Protocol.Crypto;
using DeskPair.Protocol.Framing;

string output = args.Length > 0
    ? args[0]
    : Path.Combine(AppContext.BaseDirectory, "protocol-vectors.json");

var root = new JsonObject
{
    ["_comment"] = "Generated by tools/DeskPair.Tools.Vectors from DeskPair.Protocol. Do not edit by hand.",
    ["constants"] = Constants(),
    ["keys"] = Keys(),
    ["ecdh"] = Ecdh(),
    ["ecdsa"] = Ecdsa(),
    ["transcript"] = Transcripts(),
    ["hkdf"] = Hkdf(),
    ["cipher"] = Cipher(),
    ["passwordProof"] = PasswordProofs(),
    ["relayTicket"] = RelayTicketVectors(),
    ["framing"] = Framing(),
    ["clipboard"] = Clipboards(),
    ["connectLink"] = ConnectLinks(),
    ["media"] = Media(),
};

Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(output))!);
File.WriteAllText(output, root.ToJsonString(new JsonSerializerOptions { WriteIndented = true }) + "\n");
Console.WriteLine($"Wrote {output}");
return 0;

static string Hex(ReadOnlySpan<byte> bytes) => Convert.ToHexStringLower(bytes);

// Everything the UDP media channel is made of: the three header layouts, a datagram sealed by the shipping
// cipher, and a Reed-Solomon block whose parity came from the encoder that actually runs. A phone only ever
// decodes, and a decode that is subtly wrong draws garbage rather than failing, so it is checked against the
// desktop's arithmetic instead of its own.
static JsonNode Media()
{
    // Header layouts, byte for byte. A field written at the wrong offset still round-trips through the
    // same code, so only the desktop's own bytes can catch it.
    var common = new DeskPair.Protocol.Media.MediaCommonHeader(
        DeskPair.Protocol.Media.MediaPacketType.Video,
        DeskPair.Protocol.Media.MediaPacketFlags.KeyFrame | DeskPair.Protocol.Media.MediaPacketFlags.LastShard,
        0x0102030405060708UL);
    byte[] commonBytes = new byte[DeskPair.Protocol.Media.MediaCommonHeader.Size];
    common.Write(commonBytes);

    var shard = new DeskPair.Protocol.Media.MediaShardHeader(
        Stream: 1, Codec: 2, BlockIndex: 1, BlockCount: 3,
        FrameSeq: 0x11223344u, PtsMs: 1_234_567_890L,
        ShardIndex: 5, K: 8, M: 4, ShardLength: 1100,
        FrameLength: 65_000u, Width: 2560, Height: 1440);
    byte[] shardBytes = new byte[DeskPair.Protocol.Media.MediaShardHeader.Size];
    shard.Write(shardBytes);

    var feedback = new DeskPair.Protocol.Media.MediaFeedback(
        Stream: 0, LossPermille: 37, HighestDecodableFrameSeq: 900u, LastFrameSeqReceived: 905u,
        EchoPacketSeq: 0xAABBCCDDUL, EchoDelayMicros: 12_345u, ReceivedBytes: 987_654_321UL,
        ReceiverClockMicros: 1_700_000_000_000UL, FramesGivenUp: 3u, ShardsRecovered: 17u);
    byte[] feedbackBytes = new byte[DeskPair.Protocol.Media.MediaFeedback.Size];
    feedback.Write(feedbackBytes);

    // A sealed datagram, so the phone's cipher is checked against a real one rather than against itself.
    byte[] mediaKey = Pattern(32, 0x51);
    byte[] mediaIv = Pattern(4, 0x52);
    using var cipher = new DeskPair.Protocol.Media.MediaCipher(mediaKey, mediaIv, mediaKey, mediaIv);
    var datagrams = new JsonArray();
    foreach (int length in new[] { 0, 1, 64, 517 })
    {
        byte[] plaintext = Pattern(length, 0x60);
        byte[] datagram = new byte[DeskPair.Protocol.Media.MediaCommonHeader.Size + length + DeskPair.Protocol.Media.MediaCipher.TagBytes];
        int written = cipher.Seal(DeskPair.Protocol.Media.MediaPacketType.Video, DeskPair.Protocol.Media.MediaPacketFlags.None, plaintext, datagram, out ulong seq);
        datagrams.Add(new JsonObject
        {
            ["packetSeq"] = seq,
            ["plaintext"] = Hex(plaintext),
            ["datagram"] = Hex(datagram.AsSpan(0, written)),
        });
    }

    // Reed-Solomon recovery, produced by the encoder that actually ships. Two data shards are dropped and
    // the parity that replaces them comes from the desktop, so a decoder that is subtly wrong disagrees
    // here rather than drawing garbage on someone's screen.
    const int k = 4, m = 2, shardLength = 64;
    var data = new ReadOnlyMemory<byte>[k];
    for (int i = 0; i < k; i++)
    {
        data[i] = Pattern(shardLength, (byte)(0x70 + i));
    }

    var parityBuffers = new Memory<byte>[m];
    for (int i = 0; i < m; i++)
    {
        parityBuffers[i] = new byte[shardLength];
    }

    DeskPair.Core.Transport.Udp.Fec.ReedSolomon.Encode(data, parityBuffers);

    var dataHex = new JsonArray();
    foreach (ReadOnlyMemory<byte> d in data)
    {
        dataHex.Add(Hex(d.Span));
    }

    var parityHex = new JsonArray();
    foreach (Memory<byte> p in parityBuffers)
    {
        parityHex.Add(Hex(p.Span));
    }

    var coefficients = new JsonArray();
    for (int row = 0; row < m; row++)
    {
        for (int col = 0; col < k; col++)
        {
            coefficients.Add(DeskPair.Core.Transport.Udp.Fec.ReedSolomon.Coefficient(k, row, col));
        }
    }

    return new JsonObject
    {
        ["commonHeader"] = new JsonObject
        {
            ["type"] = (int)common.Type,
            ["flags"] = (int)common.Flags,
            ["packetSeq"] = common.PacketSeq,
            ["bytes"] = Hex(commonBytes),
        },
        ["shardHeader"] = new JsonObject
        {
            ["stream"] = shard.Stream, ["codec"] = shard.Codec,
            ["blockIndex"] = shard.BlockIndex, ["blockCount"] = shard.BlockCount,
            ["frameSeq"] = shard.FrameSeq, ["ptsMs"] = shard.PtsMs,
            ["shardIndex"] = shard.ShardIndex, ["k"] = shard.K, ["m"] = shard.M,
            ["shardLength"] = shard.ShardLength, ["frameLength"] = shard.FrameLength,
            ["width"] = shard.Width, ["height"] = shard.Height,
            ["bytes"] = Hex(shardBytes),
        },
        ["feedback"] = new JsonObject
        {
            ["stream"] = feedback.Stream, ["lossPermille"] = feedback.LossPermille,
            ["highestDecodableFrameSeq"] = feedback.HighestDecodableFrameSeq,
            ["lastFrameSeqReceived"] = feedback.LastFrameSeqReceived,
            ["echoPacketSeq"] = feedback.EchoPacketSeq, ["echoDelayMicros"] = feedback.EchoDelayMicros,
            ["receivedBytes"] = feedback.ReceivedBytes, ["receiverClockMicros"] = feedback.ReceiverClockMicros,
            ["framesGivenUp"] = feedback.FramesGivenUp, ["shardsRecovered"] = feedback.ShardsRecovered,
            ["bytes"] = Hex(feedbackBytes),
        },
        ["cipher"] = new JsonObject
        {
            ["key"] = Hex(mediaKey),
            ["ivPrefix"] = Hex(mediaIv),
            ["datagrams"] = datagrams,
        },
        ["reedSolomon"] = new JsonObject
        {
            ["k"] = k, ["m"] = m, ["shardLength"] = shardLength,
            ["coefficients"] = coefficients,
            ["data"] = dataHex,
            ["parity"] = parityHex,
        },
    };
}

// The host puts its own content hash on the wire and the phone compares against it, so the two hashes have
// to agree byte for byte. Text is the only format a phone carries, but the ordering rule is exercised with
// a second item so a client that ignores the sort cannot pass.
// The pairing code's payload, written by the shipping ConnectLink. The phone has to read exactly what the
// desktop writes, and the two are separate implementations in separate languages, so the strings themselves
// are the contract rather than a description of it.
static JsonNode ConnectLinks()
{
    const string serverKey =
        "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEWjZBRYqlg374F9psEQ4ql93Qt8r7jhV3KXVO4U38xFU/dbdXpJH9l7fHFGe0NBWtNXS3uw1yYkH7i0pIYkmGwQ==";

    var cases = new JsonArray();
    foreach ((string name, DeskPair.Core.Config.ConnectLink link) in new[]
    {
        ("full", new DeskPair.Core.Config.ConnectLink
        {
            Id = "123456789",
            RendezvousServer = "203.0.113.10:21116",
            ServerPublicKeyBase64 = serverKey,
            DeviceName = "Studio-Mac-mini",
            Password = "t4nq7zkp2xmr",
        }),
        ("idOnly", new DeskPair.Core.Config.ConnectLink { Id = "123456789" }),
        ("noKey", new DeskPair.Core.Config.ConnectLink
        {
            Id = "123456789",
            RendezvousServer = "example.com",
        }),
        ("unicodeName", new DeskPair.Core.Config.ConnectLink
        {
            Id = "123456789",
            DeviceName = "辦公室 主機",
        }),
        // A host with temporary passwords switched off writes no p=, and a phone must then ask.
        ("noPassword", new DeskPair.Core.Config.ConnectLink
        {
            Id = "123456789",
            RendezvousServer = "example.com",
            ServerPublicKeyBase64 = serverKey,
        }),
    })
    {
        cases.Add(new JsonObject
        {
            ["name"] = name,
            ["text"] = link.ToString(),
            ["id"] = link.Id,
            ["rendezvousServer"] = link.RendezvousServer,
            ["serverPublicKeyBase64"] = link.ServerPublicKeyBase64,
            ["deviceName"] = link.DeviceName,
            ["password"] = link.Password,
        });
    }

    // Strings that must be refused, and why the refusal matters.
    var refused = new JsonArray
    {
        "",
        "hello",
        "https://example.com/?v=1&id=123456789",
        "rustdesk://connection/new/123456789",
        "sunllo://connect?id=123456789",
        "sunllo://connect?v=2&id=123456789",
        "sunllo://connect?v=1&rs=example.com",
        "sunllo://connect?v=1&id=123456789&k=!!!not-base64!!!",
    };

    return new JsonObject { ["version"] = DeskPair.Core.Config.ConnectLink.Version, ["cases"] = cases, ["refused"] = refused };
}

static JsonNode Clipboards()
{
    var cases = new JsonArray();
    foreach ((string name, string text) in new[]
    {
        ("ascii", "hello from the desktop"),
        ("empty", ""),
        ("unicode", "剪貼簿 — 📋"),
        ("newlines", "first\r\nsecond\nthird"),
    })
    {
        var single = new DeskPair.Protocol.Messages.MultiClipboards
        {
            Items =
            {
                new DeskPair.Protocol.Messages.Clipboard
                {
                    Format = DeskPair.Protocol.Messages.ClipboardFormat.CfText,
                    Content = Google.Protobuf.ByteString.CopyFrom(Encoding.UTF8.GetBytes(text)),
                },
            },
        };

        cases.Add(new JsonObject
        {
            ["name"] = name,
            ["text"] = text,
            ["utf8"] = Hex(Encoding.UTF8.GetBytes(text)),
            ["hash"] = Hex(DeskPair.Core.Clipboard.ClipboardSync.Hash(single)),
        });
    }

    var mixed = new DeskPair.Protocol.Messages.MultiClipboards
    {
        Items =
        {
            // Deliberately out of format order: the hash sorts, and a reimplementation that does not will
            // disagree here rather than in the field.
            new DeskPair.Protocol.Messages.Clipboard
            {
                Format = DeskPair.Protocol.Messages.ClipboardFormat.CfHtml,
                Content = Google.Protobuf.ByteString.CopyFrom(Encoding.UTF8.GetBytes("<b>bold</b>")),
            },
            new DeskPair.Protocol.Messages.Clipboard
            {
                Format = DeskPair.Protocol.Messages.ClipboardFormat.CfText,
                Content = Google.Protobuf.ByteString.CopyFrom(Encoding.UTF8.GetBytes("bold")),
            },
        },
    };

    // A real PNG rather than three arbitrary bytes: the phone encodes one from a Bitmap or a UIImage, and a
    // vector built from something that is not a PNG would not notice if either side started re-encoding.
    byte[] png = SmallPng();

    var image = new DeskPair.Protocol.Messages.MultiClipboards
    {
        Items =
        {
            new DeskPair.Protocol.Messages.Clipboard
            {
                Format = DeskPair.Protocol.Messages.ClipboardFormat.CfImagePng,
                Content = Google.Protobuf.ByteString.CopyFrom(png),
            },
        },
    };

    // Text and an image together, with the image first — CF_TEXT is 0 and CF_IMAGE_PNG is 3, so a
    // reimplementation that hashes in arrival order disagrees here. This is the case the phone actually
    // produces when someone copies a picture and a caption.
    var textAndImage = new DeskPair.Protocol.Messages.MultiClipboards
    {
        Items =
        {
            new DeskPair.Protocol.Messages.Clipboard
            {
                Format = DeskPair.Protocol.Messages.ClipboardFormat.CfImagePng,
                Content = Google.Protobuf.ByteString.CopyFrom(png),
            },
            new DeskPair.Protocol.Messages.Clipboard
            {
                Format = DeskPair.Protocol.Messages.ClipboardFormat.CfText,
                Content = Google.Protobuf.ByteString.CopyFrom(Encoding.UTF8.GetBytes("a caption")),
            },
        },
    };

    return new JsonObject
    {
        ["text"] = cases,
        ["ordering"] = new JsonObject
        {
            ["html"] = "<b>bold</b>",
            ["text"] = "bold",
            ["hash"] = Hex(DeskPair.Core.Clipboard.ClipboardSync.Hash(mixed)),
        },
        ["image"] = new JsonObject
        {
            ["png"] = Hex(png),
            ["width"] = 4,
            ["height"] = 3,
            ["hash"] = Hex(DeskPair.Core.Clipboard.ClipboardSync.Hash(image)),
        },
        ["textAndImage"] = new JsonObject
        {
            ["text"] = "a caption",
            ["png"] = Hex(png),
            ["hash"] = Hex(DeskPair.Core.Clipboard.ClipboardSync.Hash(textAndImage)),
        },
        ["maxBytes"] = DeskPair.Protocol.ProtocolConstants.MaxClipboardBytes,
    };
}

// A 4x3 PNG from the shipping encoder, so the bytes are ones the product itself produces.
static byte[] SmallPng()
{
    const int width = 4, height = 3;
    byte[] bgra = new byte[width * height * 4];
    for (int i = 0; i < width * height; i++)
    {
        bgra[(i * 4) + 0] = (byte)(i * 20);        // blue
        bgra[(i * 4) + 1] = (byte)(255 - (i * 20)); // green
        bgra[(i * 4) + 2] = (byte)(i * 7);          // red
        bgra[(i * 4) + 3] = 0xFF;                   // opaque
    }

    return DeskPair.Platform.Abstractions.Imaging.PngCodec.Encode(bgra, width * 4, width, height);
}

// Deterministic filler, so the same run always produces the same file.
static byte[] Pattern(int length, byte seed)
{
    byte[] bytes = new byte[length];
    for (int i = 0; i < length; i++)
    {
        bytes[i] = (byte)((i * 31) + seed);
    }

    return bytes;
}

static JsonObject Constants() => new()
{
    ["protocolVersion"] = ProtocolConstants.ProtocolVersion,
    ["minProtocolVersion"] = ProtocolConstants.MinProtocolVersion,
    ["legacyHelloVersion"] = ProtocolConstants.LegacyHelloVersion,
    ["pbkdf2DefaultIterations"] = PasswordProof.DefaultIterations,
    ["pbkdf2MaxIterations"] = PasswordProof.MaxIterations,
    ["relayTicketMaxBytes"] = RelayTickets.MaxBytes,
    ["frameHeaderBytes"] = FramedStream.HeaderBytes,
    ["encryptedFlag"] = "0x80000000",
    ["lengthMask"] = "0x3fffffff",
    ["tagBytes"] = SessionCipher.TagBytes,
    ["cipherNonceBytes"] = SessionCipher.NonceBytes,
    ["keyBytes"] = SessionKeys.KeyBytes,
    ["ivPrefixBytes"] = SessionKeys.IvPrefixBytes,
    ["handshakeNonceBytes"] = ProtocolConstants.NonceBytes,
    ["saltBytes"] = ProtocolConstants.SaltBytes,
    ["challengeBytes"] = ProtocolConstants.ChallengeBytes,
    ["signatureBytes"] = IdentityKey.SignatureBytes,
    ["maxPeerFrameBytes"] = ProtocolConstants.MaxPeerFrameBytes,
    ["maxControlFrameBytes"] = ProtocolConstants.MaxControlFrameBytes,
    ["rendezvousPort"] = ProtocolConstants.RendezvousPort,
    ["relayPort"] = ProtocolConstants.RelayPort,
    ["directAccessPort"] = ProtocolConstants.DirectAccessPort,
    ["natTestPort"] = ProtocolConstants.NatTestPort,
};

// SPKI round trips. A P-256 public key is 91 bytes of DER and a reimplementation that hand-rolls the
// encoding gets the OID sequence or the leading 0x04 wrong; this is the cheapest possible way to find out.
static JsonArray Keys()
{
    var array = new JsonArray();
    foreach (byte seed in new byte[] { 1, 2, 3 })
    {
        using ECDsa key = DeterministicEcdsa(seed);
        byte[] spki = key.ExportSubjectPublicKeyInfo();
        ECParameters p = key.ExportParameters(includePrivateParameters: false);
        array.Add(new JsonObject
        {
            ["curve"] = "P-256",
            ["x"] = Hex(p.Q.X!),
            ["y"] = Hex(p.Q.Y!),
            ["spki"] = Hex(spki),
            ["fingerprintSha256"] = IdentityKey.Fingerprint(spki).ToLowerInvariant(),
        });
    }

    return array;
}

// The shared secret is the raw X coordinate and is NOT hashed (EphemeralKey.DeriveRawSecret). Almost every
// other protocol hashes it, so this is exactly the detail a second implementation gets wrong, and it would
// fail with a tag mismatch three messages later rather than here.
static JsonArray Ecdh()
{
    var array = new JsonArray();
    for (byte seed = 10; seed < 13; seed++)
    {
        using ECDiffieHellman a = DeterministicEcdh(seed);
        using ECDiffieHellman b = DeterministicEcdh((byte)(seed + 100));
        using ECDiffieHellmanPublicKey bPublic = b.PublicKey;
        array.Add(new JsonObject
        {
            ["privatePkcs8"] = Hex(a.ExportPkcs8PrivateKey()),
            ["peerSpki"] = Hex(b.ExportSubjectPublicKeyInfo()),
            ["rawSecret"] = Hex(a.DeriveRawSecretAgreement(bPublic)),
        });
    }

    return array;
}

// Signatures are 64-byte r||s (IEEE P1363), not DER, and are made over SHA-256 of the data. Includes one
// signature that must NOT verify, so an implementation that returns true unconditionally fails too.
//
// The signatures are frozen rather than produced on each run, because ECDSA picks k at random and a file
// that changes every run cannot be diffed or reviewed. They are still checked against the shipping code
// before anything is written: if the signature format ever changed, this throws instead of emitting a
// vector that quietly disagrees with reality.
static JsonArray Ecdsa()
{
    (int Length, string Signature, bool Verifies)[] frozen =
    [
        (0, "a829bedc1afe161313ad3ec04a4ce0ad6f5e6caa8c6e93cbb8882c90003bb58313a9b8dd9122ac5e9aca5b375850aa945c3f78845faa0d45c9aa6dc1c659736d", true),
        (32, "dbacbfa0fd9e191797874c70abf7862cefc2d4bb5be370bb69c54f5f5f945b953c5c7044ca8869bca8f724b4a3cef142b275797b25c0532f9bd39f1022e30422", true),
        (137, "40b0b857059ecaeea2f5bfeb321d1c8cec757174b1e5e68e19a47902c00138b3dbc3aad33ff25b8ebd010fbcfcd8d203e84373c33b58be2b86cd4722f2fbcb41", true),
        (-1, "b1c5ef0f6224c27c582fda773cca4f5414647e7682a3888229d7424f69157fe74de42d3155f79e69a86b982c374d251d7f18b335026b409db4285599ea5aa458", false),
    ];

    var array = new JsonArray();
    using ECDsa key = DeterministicEcdsa(7);
    byte[] spki = key.ExportSubjectPublicKeyInfo();

    foreach ((int length, string signatureHex, bool verifies) in frozen)
    {
        // -1 stands for the tampered case, whose message is the literal "hello".
        byte[] message = length < 0 ? "hello"u8.ToArray() : Pattern(length, 0x5a);
        byte[] signature = Convert.FromHexString(signatureHex);

        if (IdentityKey.Verify(spki, message, signature) != verifies)
        {
            throw new InvalidOperationException(
                $"A frozen ECDSA vector no longer behaves as recorded (message of {message.Length} bytes, expected verifies={verifies}). " +
                "The signature format or the deterministic key derivation has changed; regenerate these values deliberately.");
        }

        array.Add(new JsonObject
        {
            ["spki"] = Hex(spki),
            ["message"] = Hex(message),
            ["signature"] = Hex(signature),
            ["verifies"] = verifies,
        });
    }

    return array;
}

// The exact bytes the host signs: "SunlloHS1" with no length prefix, then six fields each prefixed by its
// length as a uint32 little-endian, in host-then-controller order.
static JsonArray Transcripts()
{
    var array = new JsonArray();
    foreach (string hostId in new[] { "123456789", "LAN-4EE58637", string.Empty })
    {
        using ECDsa identity = DeterministicEcdsa(20);
        using ECDiffieHellman ephH = DeterministicEcdh(21);
        using ECDiffieHellman ephC = DeterministicEcdh(22);
        byte[] identityPk = identity.ExportSubjectPublicKeyInfo();
        byte[] ephHostPk = ephH.ExportSubjectPublicKeyInfo();
        byte[] ephControllerPk = ephC.ExportSubjectPublicKeyInfo();
        byte[] nonceH = Pattern(ProtocolConstants.NonceBytes, 0x11);
        byte[] nonceC = Pattern(ProtocolConstants.NonceBytes, 0x22);

        array.Add(new JsonObject
        {
            ["hostId"] = hostId,
            ["identityPk"] = Hex(identityPk),
            ["hostEphemeralPk"] = Hex(ephHostPk),
            ["hostNonce"] = Hex(nonceH),
            ["controllerEphemeralPk"] = Hex(ephControllerPk),
            ["controllerNonce"] = Hex(nonceC),
            ["hash"] = Hex(Handshake.Transcript(hostId, identityPk, ephHostPk, nonceH, ephControllerPk, nonceC)),
        });
    }

    return array;
}

// All eight HKDF outputs from one handshake, salted with the controller nonce first. The media keys are
// included even though phase 1 declines UDP: getting them wrong later is much harder to notice.
static JsonArray Hkdf()
{
    var array = new JsonArray();
    for (byte seed = 30; seed < 32; seed++)
    {
        using ECDiffieHellman controller = DeterministicEcdh(seed);
        using ECDiffieHellman host = DeterministicEcdh((byte)(seed + 50));
        byte[] nonceC = Pattern(ProtocolConstants.NonceBytes, seed);
        byte[] nonceH = Pattern(ProtocolConstants.NonceBytes, (byte)(seed + 1));

        using EphemeralKey controllerKey = EphemeralKeyFrom(controller);
        using SessionKeys keys = Handshake.Derive(controllerKey, host.ExportSubjectPublicKeyInfo(), nonceC, nonceH, isHost: false);
        MediaKeys media = keys.ExportMediaKeys();

        array.Add(new JsonObject
        {
            ["controllerPrivatePkcs8"] = Hex(controller.ExportPkcs8PrivateKey()),
            ["hostEphemeralSpki"] = Hex(host.ExportSubjectPublicKeyInfo()),
            ["controllerNonce"] = Hex(nonceC),
            ["hostNonce"] = Hex(nonceH),
            // Named from the controller's point of view: tx is what it encrypts with, rx what it decrypts with.
            ["txKey"] = Hex(keys.TxKey),
            ["txIvPrefix"] = Hex(keys.TxIvPrefix),
            ["rxKey"] = Hex(keys.RxKey),
            ["rxIvPrefix"] = Hex(keys.RxIvPrefix),
            ["mediaTxKey"] = Hex(media.TxKey),
            ["mediaTxIvPrefix"] = Hex(media.TxIvPrefix),
            ["mediaRxKey"] = Hex(media.RxKey),
            ["mediaRxIvPrefix"] = Hex(media.RxIvPrefix),
        });
        media.Dispose();
    }

    return array;
}

// A run of frames through one cipher, proving the nonce discipline: the counter starts at 1, increments per
// encrypted frame, and the 4-byte frame header is the associated data. Nothing on the wire carries the
// counter, so an implementation that starts at 0 produces garbage on the very first frame — and one that
// forgets the associated data produces garbage only when someone tampers, which is worse.
static JsonArray Cipher()
{
    var array = new JsonArray();
    byte[] key = Pattern(SessionKeys.KeyBytes, 0x40);
    byte[] ivPrefix = Pattern(SessionKeys.IvPrefixBytes, 0x50);

    using var cipher = new SessionCipher(key, ivPrefix);
    var frames = new JsonArray();
    foreach (int length in new[] { 1, 16, 255, 4096 })
    {
        byte[] plaintext = Pattern(length, 0x60);
        byte[] header = new byte[FramedStream.HeaderBytes];
        BinaryPrimitives.WriteUInt32LittleEndian(header, (uint)(plaintext.Length + SessionCipher.TagBytes) | 0x8000_0000u);

        byte[] ciphertext = new byte[plaintext.Length];
        byte[] tag = new byte[SessionCipher.TagBytes];
        cipher.Encrypt(plaintext, ciphertext, tag, header);

        frames.Add(new JsonObject
        {
            ["counter"] = cipher.Counter,
            ["header"] = Hex(header),
            ["plaintext"] = Hex(plaintext),
            ["ciphertext"] = Hex(ciphertext),
            ["tag"] = Hex(tag),
        });
    }

    array.Add(new JsonObject
    {
        ["key"] = Hex(key),
        ["ivPrefix"] = Hex(ivPrefix),
        ["frames"] = frames,
    });

    return array;
}

// Both derivations the challenge can name. The single hash is protocol 1's and stays for hosts whose
// permanent password predates protocol 2; PBKDF2 is what a host derives today. A phone that gets the
// derivation wrong is told "wrong password" by a host it typed the right one into, which is the kind of
// failure nobody can debug from a screenshot -- hence the vectors. Iterations are kept small here so the
// Kotlin/Native test run stays quick; the count is an input, not a constant.
static JsonArray PasswordProofs()
{
    var array = new JsonArray();
    foreach (string password in new[] { "feps26", string.Empty, "密碼 with spaces ☃" })
    {
        foreach ((DeskPair.Protocol.Messages.PasswordKdf kdf, int iterations) in new[]
        {
            (DeskPair.Protocol.Messages.PasswordKdf.KdfSha256, 0),
            (DeskPair.Protocol.Messages.PasswordKdf.KdfPbkdf2Sha256, 4096),
        })
        {
            byte[] salt = Pattern(ProtocolConstants.SaltBytes, 0x70);
            byte[] challenge = Pattern(ProtocolConstants.ChallengeBytes, 0x80);
            byte[] h1 = PasswordProof.ComputeH1(password, salt, kdf, iterations);
            array.Add(new JsonObject
            {
                ["password"] = password,
                ["passwordUtf8"] = Hex(Encoding.UTF8.GetBytes(password)),
                ["salt"] = Hex(salt),
                ["challenge"] = Hex(challenge),
                ["kdf"] = (int)kdf,
                ["iterations"] = iterations,
                ["h1"] = Hex(h1),
                ["proof"] = Hex(PasswordProof.ComputeProof(h1, challenge)),
            });
        }
    }

    return array;
}

// A relay ticket signed by a deterministic server key, its derived UDP token, and the bind datagram that
// carries it -- and three tickets that must not verify. The phone only ever presents tickets, but it
// derives the UDP token itself, and a token derived differently pairs with nobody.
static JsonNode RelayTicketVectors()
{
    using ECDsa serverEcdsa = DeterministicEcdsa(7);
    using IdentityKey server = IdentityKey.FromPkcs8(serverEcdsa.ExportPkcs8PrivateKey());
    using ECDsa otherEcdsa = DeterministicEcdsa(8);
    using IdentityKey other = IdentityKey.FromPkcs8(otherEcdsa.ExportPkcs8PrivateKey());
    DateTimeOffset now = DateTimeOffset.FromUnixTimeSeconds(1_790_000_000);
    const string uuid = "0123456789abcdef0123456789abcdef";

    DeskPair.Protocol.Rendezvous.RelayTicket good = RelayTickets.Issue(server, uuid, string.Empty, now.AddMinutes(2));
    byte[] token = RelayTickets.UdpToken(good);
    byte[] bind = new byte[DeskPair.Protocol.Media.RelayDatagram.MaxSize];
    int bindLength = DeskPair.Protocol.Media.RelayDatagram.WriteBindTicket(bind, token, Google.Protobuf.MessageExtensions.ToByteArray(good));

    JsonObject Ticket(DeskPair.Protocol.Rendezvous.RelayTicket t) => new()
    {
        ["payload"] = Hex(t.Payload.Span),
        ["signature"] = Hex(t.Signature.Span),
        ["encoded"] = Hex(Google.Protobuf.MessageExtensions.ToByteArray(t)),
    };

    return new JsonObject
    {
        ["serverPublicKeySpki"] = Hex(server.PublicKeySpki),
        ["nowUnix"] = now.ToUnixTimeSeconds(),
        ["uuid"] = uuid,
        ["ticket"] = Ticket(good),
        ["udpToken"] = Hex(token),
        ["bindDatagram"] = Hex(bind.AsSpan(0, bindLength)),
        ["refused"] = new JsonArray
        {
            new JsonObject { ["why"] = "expired", ["ticket"] = Ticket(RelayTickets.Issue(server, uuid, string.Empty, now.AddMinutes(-1))) },
            new JsonObject { ["why"] = "other key", ["ticket"] = Ticket(RelayTickets.Issue(other, uuid, string.Empty, now.AddMinutes(2))) },
            new JsonObject { ["why"] = "other uuid", ["ticket"] = Ticket(RelayTickets.Issue(server, "ffffffffffffffffffffffffffffffff", string.Empty, now.AddMinutes(2))) },
        },
    };
}

// Header encodings and the frames that must be refused. The parser rejects a heartbeat with the encrypted
// bit set, and an encrypted frame shorter than a tag; both are cheap to get wrong and impossible to notice
// until something malicious arrives.
static JsonArray Framing()
{
    var array = new JsonArray();

    void Add(string description, uint header, bool valid, int? payloadLength = null, bool encrypted = false, bool heartbeat = false)
    {
        byte[] bytes = new byte[FramedStream.HeaderBytes];
        BinaryPrimitives.WriteUInt32LittleEndian(bytes, header);
        var entry = new JsonObject
        {
            ["description"] = description,
            ["header"] = Hex(bytes),
            ["valid"] = valid,
            ["encrypted"] = encrypted,
            ["heartbeat"] = heartbeat,
        };
        if (payloadLength is { } n)
        {
            entry["bodyLength"] = n;
        }

        array.Add(entry);
    }

    Add("empty header is a heartbeat", 0u, valid: true, payloadLength: 0, heartbeat: true);
    Add("plaintext frame of 5 bytes", 5u, valid: true, payloadLength: 5);
    Add("encrypted frame of 17 bytes, the smallest legal one", 17u | 0x8000_0000u, valid: true, payloadLength: 17, encrypted: true);
    Add("encrypted heartbeat is refused", 0u | 0x8000_0000u, valid: false, heartbeat: true, encrypted: true);
    Add("encrypted frame shorter than a tag is refused", 16u | 0x8000_0000u, valid: false, encrypted: true);
    Add("length over the peer cap is refused", (uint)ProtocolConstants.MaxPeerFrameBytes + 1u, valid: false);

    return array;
}

// ---- deterministic key material -------------------------------------------------------------------------
//
// ECDsa.Create() would give a different key every run and a vector file nobody can diff. These derive the
// private scalar from a seed instead, then let the BCL compute the public point.

static ECParameters DeterministicParameters(byte seed)
{
    // Any 32-byte value below the P-256 group order is a valid private scalar; SHA-256 of the seed is one,
    // with the top byte cleared so it can never exceed the order.
    byte[] d = SHA256.HashData([seed, 0x9e, 0x37, 0x79, 0xb9]);
    d[0] &= 0x7f;

    using ECDiffieHellman scratch = ECDiffieHellman.Create(ECCurve.NamedCurves.nistP256);
    ECParameters template = scratch.ExportParameters(includePrivateParameters: true);
    template.D = d;

    // Recomputing Q from D is not exposed by the BCL, so import with D only and let it derive the point.
    var parameters = new ECParameters { Curve = ECCurve.NamedCurves.nistP256, D = d };
    using ECDiffieHellman derived = ECDiffieHellman.Create(parameters);
    return derived.ExportParameters(includePrivateParameters: true);
}

static ECDsa DeterministicEcdsa(byte seed) => ECDsa.Create(DeterministicParameters(seed));

static ECDiffieHellman DeterministicEcdh(byte seed) => ECDiffieHellman.Create(DeterministicParameters(seed));

static EphemeralKey EphemeralKeyFrom(ECDiffieHellman key) => EphemeralKey.FromPkcs8(key.ExportPkcs8PrivateKey());
