using SkiaSharp;

// Draws the DeskPair mark (assets/logo/*.svg) at any size and writes every icon the product needs: the PNG
// set, the Windows .ico, the Android launcher mipmaps and the iOS app icon.
// The geometry here is the same 256-unit construction as the SVGs: a 176 square rotated 45 degrees with
// corner radius 30, cut by two 24-wide chevrons offset 16 units above and below the centre line.
//   dotnet run --project tools/DeskPair.Tools.IconGen -- [output root]

string root = args.Length > 0 ? args[0] : Directory.GetCurrentDirectory();
string pngDir = Path.Combine(root, "assets", "logo", "png");
string icoPath = Path.Combine(root, "src", "DeskPair.Desktop", "Assets", "deskpair.ico");
Directory.CreateDirectory(pngDir);
Directory.CreateDirectory(Path.GetDirectoryName(icoPath)!);

int[] pngSizes = [16, 24, 32, 48, 64, 128, 256, 512];
int[] icoSizes = [16, 20, 24, 32, 48, 64, 128, 256];

foreach (int size in pngSizes)
{
    File.WriteAllBytes(Path.Combine(pngDir, $"deskpair-{size}.png"), Render(size, Art.Mark));
    File.WriteAllBytes(Path.Combine(pngDir, $"deskpair-tile-{size}.png"), Render(size, Art.Tile));
}

// Small sizes use the transparent mark (a tile's rounded square would eat most of a 16 px icon);
// from 48 up the navy tile reads better on the taskbar and in the installer.
File.WriteAllBytes(icoPath, Ico(icoSizes.Select(s => (s, Render(s, s >= 48 ? Art.Tile : Art.Mark))).ToList()));
Console.WriteLine($"wrote {pngSizes.Length * 2} PNGs to {pngDir}");
Console.WriteLine($"wrote {icoPath} ({icoSizes.Length} sizes)");

WriteAndroid(Path.Combine(root, "mobile", "androidApp", "src", "main", "res"));
WriteApple(Path.Combine(root, "mobile", "iosApp", "iosApp", "Assets.xcassets"));
return 0;

// Android's launcher icons, in the three shapes the platform asks for.
//
// An adaptive icon is two layers the launcher masks to whatever shape the device uses — a circle, a squircle,
// a rounded square — and it may be scaled up and parallaxed, so only the middle 72 of its 108 units are
// guaranteed to survive. The mark therefore goes in at two thirds, on a flat navy background rather than the
// tile's gradient: the launcher owns the shape, so a rounded rectangle drawn here would show through as a
// second, wrong outline. The chevrons stay painted white here rather than cut out as they are on the tile:
// a launcher may parallax the two layers independently, and holes would then slide across the background.
// The legacy PNGs underneath are for pre-Oreo launchers, which mask nothing, and those do get the tile.
static void WriteAndroid(string resDir)
{
    if (!Directory.Exists(Path.GetDirectoryName(resDir)))
    {
        Console.WriteLine($"skipped Android icons: {resDir} has no parent");
        return;
    }

    // Density buckets, as multiples of the baseline. Legacy launcher icons are 48 dp, adaptive layers 108 dp.
    (string Bucket, double Scale)[] densities =
    [
        ("mdpi", 1.0), ("hdpi", 1.5), ("xhdpi", 2.0), ("xxhdpi", 3.0), ("xxxhdpi", 4.0),
    ];

    foreach ((string bucket, double scale) in densities)
    {
        string dir = Path.Combine(resDir, $"mipmap-{bucket}");
        Directory.CreateDirectory(dir);

        int legacy = (int)Math.Round(48 * scale);
        int adaptive = (int)Math.Round(108 * scale);

        File.WriteAllBytes(Path.Combine(dir, "ic_launcher.png"), Render(legacy, Art.Tile));
        File.WriteAllBytes(Path.Combine(dir, "ic_launcher_round.png"), Render(legacy, Art.RoundTile));
        File.WriteAllBytes(Path.Combine(dir, "ic_launcher_foreground.png"), Render(adaptive, Art.Mark, Zones.Adaptive));
        File.WriteAllBytes(Path.Combine(dir, "ic_launcher_monochrome.png"), Render(adaptive, Art.Mono, Zones.Adaptive));
    }

    string anyDpi = Path.Combine(resDir, "mipmap-anydpi-v26");
    Directory.CreateDirectory(anyDpi);
    foreach (string name in new[] { "ic_launcher.xml", "ic_launcher_round.xml" })
    {
        File.WriteAllText(
            Path.Combine(anyDpi, name),
            """
            <?xml version="1.0" encoding="utf-8"?>
            <!-- Generated by tools/DeskPair.Tools.IconGen. Do not edit by hand. -->
            <adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
                <background android:drawable="@color/ic_launcher_background" />
                <foreground android:drawable="@mipmap/ic_launcher_foreground" />
                <monochrome android:drawable="@mipmap/ic_launcher_monochrome" />
            </adaptive-icon>

            """);
    }

    Console.WriteLine($"wrote Android mipmaps to {resDir} ({densities.Length} densities)");
}

// The iOS asset catalogue. Xcode 14 and later take a single 1024 icon and derive every size it needs, so
// there is one PNG here rather than the old fifteen.
static void WriteApple(string catalogue)
{
    if (!Directory.Exists(Path.GetDirectoryName(catalogue)))
    {
        Console.WriteLine($"skipped iOS icons: {catalogue} has no parent");
        return;
    }

    string appIcon = Path.Combine(catalogue, "AppIcon.appiconset");
    Directory.CreateDirectory(appIcon);

    // Opaque and square-cornered. An iOS app icon may not carry an alpha channel — a transparent mark
    // would be composited onto black by the asset compiler with no say from us — and iOS applies its own
    // superellipse mask, so drawing the tile's own rounded corners here would only leave flat navy in the
    // four corners where the gradient should still be running.
    File.WriteAllBytes(Path.Combine(appIcon, "AppIcon-1024.png"), Render(1024, Art.SquareTile, opaque: true));

    File.WriteAllText(
        Path.Combine(appIcon, "Contents.json"),
        """
        {
          "images" : [
            {
              "filename" : "AppIcon-1024.png",
              "idiom" : "universal",
              "platform" : "ios",
              "size" : "1024x1024"
            }
          ],
          "info" : {
            "author" : "xcode",
            "version" : 1
          }
        }

        """);

    Console.WriteLine($"wrote {appIcon}");
}

static byte[] Render(int size, Art art, float fraction = 1f, bool opaque = false)
{
    var info = new SKImageInfo(size, size, SKColorType.Rgba8888, opaque ? SKAlphaType.Opaque : SKAlphaType.Premul);
    using var surface = SKSurface.Create(info);
    SKCanvas canvas = surface.Canvas;
    canvas.Clear(opaque ? Hex("#001839") : SKColors.Transparent);
    canvas.Scale(size / 256f);

    if (fraction != 1f)
    {
        canvas.Translate(128, 128);
        canvas.Scale(fraction);
        canvas.Translate(-128, -128);
    }

    switch (art)
    {
        case Art.Tile:
            DrawTile(canvas, Edge.Rounded);
            break;
        case Art.RoundTile:
            DrawTile(canvas, Edge.Circle);
            break;
        case Art.SquareTile:
            DrawTile(canvas, Edge.Square);
            break;
        case Art.Mono:
            DrawMonochrome(canvas);
            break;
        default:
            DrawMark(canvas);
            break;
    }

    using SKImage image = surface.Snapshot();
    using SKData data = image.Encode(SKEncodedImageFormat.Png, 100);
    return data.ToArray();
}

static void DrawMark(SKCanvas canvas)
{
    canvas.Save();
    canvas.RotateDegrees(45, 128, 128);
    using (var body = new SKPaint { IsAntialias = true })
    {
        body.Shader = SKShader.CreateLinearGradient(
            new SKPoint(46, 46),
            new SKPoint(210, 210),
            [Hex("#74d7ea"), Hex("#0aa9d1"), Hex("#418bd6"), Hex("#003c7e")],
            [0f, 0.35f, 0.72f, 1f],
            SKShaderTileMode.Clamp);
        canvas.DrawRoundRect(new SKRect(40, 40, 216, 216), 30, 30, body);
    }

    using (var sheen = new SKPaint { IsAntialias = true })
    {
        sheen.Shader = SKShader.CreateRadialGradient(
            new SKPoint(92, 80),
            150,
            [new SKColor(255, 255, 255, 97), new SKColor(255, 255, 255, 15), new SKColor(255, 255, 255, 0)],
            [0f, 0.55f, 1f],
            SKShaderTileMode.Clamp);
        canvas.DrawRoundRect(new SKRect(40, 40, 216, 216), 30, 30, sheen);
    }

    canvas.Restore();
    using var chevrons = new SKPaint
    {
        IsAntialias = true,
        Style = SKPaintStyle.Stroke,
        StrokeWidth = 24,
        StrokeCap = SKStrokeCap.Round,
        StrokeJoin = SKStrokeJoin.Round,
        Color = SKColors.White,
    };
    canvas.DrawPath(LeftChevron(), chevrons);
    canvas.DrawPath(RightChevron(), chevrons);
}

static void DrawTile(SKCanvas canvas, Edge edge)
{
    using (var background = new SKPaint { IsAntialias = true })
    {
        background.Shader = SKShader.CreateLinearGradient(
            new SKPoint(0, 0),
            new SKPoint(256, 256),
            [Hex("#002559"), Hex("#001839")],
            [0f, 1f],
            SKShaderTileMode.Clamp);
        switch (edge)
        {
            case Edge.Circle:
                canvas.DrawCircle(128, 128, 128, background);
                break;
            case Edge.Square:
                canvas.DrawRect(new SKRect(0, 0, 256, 256), background);
                break;
            default:
                canvas.DrawRoundRect(new SKRect(0, 0, 256, 256), 56, 56, background);
                break;
        }
    }

    // The diamond sits at 72 % inside the tile, and the chevrons are cut out of it rather than drawn on top.
    canvas.Save();
    canvas.Translate(128, 128);
    canvas.Scale(0.72f);
    canvas.Translate(-128, -128);
    canvas.SaveLayer(null);
    canvas.Save();
    canvas.RotateDegrees(45, 128, 128);
    using (var body = new SKPaint { IsAntialias = true })
    {
        body.Shader = SKShader.CreateLinearGradient(
            new SKPoint(70, 70),
            new SKPoint(186, 186),
            [Hex("#74d7ea"), Hex("#0aa9d1"), Hex("#418bd6"), Hex("#0d5ba6")],
            [0f, 0.35f, 0.72f, 1f],
            SKShaderTileMode.Clamp);
        canvas.DrawRoundRect(new SKRect(40, 40, 216, 216), 30, 30, body);
    }

    canvas.Restore();
    using (var cut = new SKPaint
    {
        IsAntialias = true,
        Style = SKPaintStyle.Stroke,
        StrokeWidth = 24,
        StrokeCap = SKStrokeCap.Round,
        StrokeJoin = SKStrokeJoin.Round,
        BlendMode = SKBlendMode.Clear,
    })
    {
        canvas.DrawPath(LeftChevron(), cut);
        canvas.DrawPath(RightChevron(), cut);
    }

    canvas.Restore();
    canvas.Restore();
}

// The themed-icon layer, matching assets/logo/deskpair-mono.svg: one solid shape with the chevrons
// knocked out, which Android recolours to whatever the wallpaper's palette says. Drawn black because only
// the alpha survives the tint.
static void DrawMonochrome(SKCanvas canvas)
{
    canvas.SaveLayer(null);
    canvas.Save();
    canvas.RotateDegrees(45, 128, 128);
    using (var body = new SKPaint { IsAntialias = true, Color = SKColors.Black })
    {
        canvas.DrawRoundRect(new SKRect(40, 40, 216, 216), 30, 30, body);
    }

    canvas.Restore();
    using (var cut = new SKPaint
    {
        IsAntialias = true,
        Style = SKPaintStyle.Stroke,
        StrokeWidth = 24,
        StrokeCap = SKStrokeCap.Round,
        StrokeJoin = SKStrokeJoin.Round,
        BlendMode = SKBlendMode.Clear,
    })
    {
        canvas.DrawPath(LeftChevron(), cut);
        canvas.DrawPath(RightChevron(), cut);
    }

    canvas.Restore();
}

static SKPath LeftChevron()
{
    var path = new SKPath();
    path.MoveTo(117, 100);
    path.LineTo(74, 144);
    path.LineTo(117, 188);
    return path;
}

static SKPath RightChevron()
{
    var path = new SKPath();
    path.MoveTo(139, 68);
    path.LineTo(182, 112);
    path.LineTo(139, 156);
    return path;
}

static SKColor Hex(string value) => SKColor.Parse(value);

// Packs PNG-encoded images into a Windows .ico; Windows Vista and later read PNG entries at every size.
static byte[] Ico(List<(int Size, byte[] Png)> images)
{
    using var stream = new MemoryStream();
    using var writer = new BinaryWriter(stream);
    writer.Write((ushort)0); // reserved
    writer.Write((ushort)1); // type: icon
    writer.Write((ushort)images.Count);
    int offset = 6 + (16 * images.Count);
    foreach ((int size, byte[] png) in images)
    {
        writer.Write((byte)(size >= 256 ? 0 : size));
        writer.Write((byte)(size >= 256 ? 0 : size));
        writer.Write((byte)0); // colours in palette
        writer.Write((byte)0); // reserved
        writer.Write((ushort)1); // colour planes
        writer.Write((ushort)32); // bits per pixel
        writer.Write(png.Length);
        writer.Write(offset);
        offset += png.Length;
    }

    foreach ((_, byte[] png) in images)
    {
        writer.Write(png);
    }

    writer.Flush();
    return stream.ToArray();
}

/// <summary>Which of the mark's four forms to draw.</summary>
internal enum Art
{
    /// <summary>The diamond on transparency, chevrons painted white on top.</summary>
    Mark,

    /// <summary>The navy rounded square with the diamond inside and the chevrons cut through it.</summary>
    Tile,

    /// <summary>The same tile on a circle, for launchers that ask for a round icon and mask nothing.</summary>
    RoundTile,

    /// <summary>The tile with no corners of its own, for a platform that applies its own mask.</summary>
    SquareTile,

    /// <summary>One solid shape with the chevrons knocked out, for Android's themed icons.</summary>
    Mono,
}

/// <summary>The outline a tile is cut to.</summary>
internal enum Edge
{
    /// <summary>The brand's own 56-unit radius.</summary>
    Rounded,

    /// <summary>A full circle.</summary>
    Circle,

    /// <summary>Full bleed, for a platform that masks the icon itself.</summary>
    Square,
}

/// <summary>
/// How much of an adaptive icon's 108 units a launcher promises to show: the middle 72.
/// </summary>
internal static class Zones
{
    public const float Adaptive = 72f / 108f;
}
