package com.sunllo.deskpair.android

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import android.util.Log
import com.sunllo.deskpair.store.SecretStore
import com.sunllo.deskpair.store.SettingsStorage
import java.io.File
import java.security.GeneralSecurityException
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Secrets under a key the hardware keystore holds.
 *
 * Not `androidx.security:security-crypto`: EncryptedSharedPreferences was deprecated in 2025 with nothing
 * put in its place, and what it does is this — an AES-GCM key in the AndroidKeyStore over ordinary
 * preferences. Doing it directly is sixty lines, adds no dependency, and cannot be deprecated out from
 * under the app.
 *
 * What is stored here is pinned fingerprints and, if the user asks, passwords. A fingerprint is public;
 * it is kept here for integrity rather than secrecy, because anyone who can rewrite the pin file defeats
 * trust-on-first-use entirely.
 */
class AndroidSecretStore(context: Context) : SecretStore {

    private val prefs = context.applicationContext.getSharedPreferences(FILE, Context.MODE_PRIVATE)

    override fun get(key: String): String? {
        val stored = prefs.getString(key, null) ?: return null
        return try {
            decrypt(stored)
        } catch (e: GeneralSecurityException) {
            // The keystore key can genuinely disappear — a restored backup, or the user changing their
            // lock screen credential on some devices. Treating that as "nothing stored" is what the
            // desktop's WindowsSecretStore does with a DPAPI failure, and it fails safe: a lost pin is
            // asked again, where a thrown exception here would take the app down at launch.
            Log.w(TAG, "A stored secret could not be read and has been discarded.", e)
            prefs.edit().remove(key).apply()
            null
        }
    }

    override fun set(key: String, value: String) {
        prefs.edit().putString(key, encrypt(value)).apply()
    }

    override fun remove(key: String) {
        prefs.edit().remove(key).apply()
    }

    override fun keys(prefix: String): List<String> =
        prefs.all.keys.filter { it.startsWith(prefix) }

    private fun encrypt(value: String): String {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey())
        val body = cipher.doFinal(value.toByteArray(Charsets.UTF_8))
        // The IV is generated by the keystore and must be kept; it is not secret.
        return Base64.encodeToString(cipher.iv + body, Base64.NO_WRAP)
    }

    private fun decrypt(stored: String): String {
        val raw = Base64.decode(stored, Base64.NO_WRAP)
        if (raw.size <= IV_BYTES) {
            throw GeneralSecurityException("Stored secret is too short to contain an IV.")
        }

        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(
            Cipher.DECRYPT_MODE,
            secretKey(),
            GCMParameterSpec(TAG_BITS, raw, 0, IV_BYTES),
        )
        return String(cipher.doFinal(raw, IV_BYTES, raw.size - IV_BYTES), Charsets.UTF_8)
    }

    private fun secretKey(): SecretKey {
        val keystore = KeyStore.getInstance(KEYSTORE).apply { load(null) }
        (keystore.getEntry(ALIAS, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE)
        generator.init(
            KeyGenParameterSpec.Builder(
                ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                // Deliberately not requiring user authentication: the app has to be able to reconnect
                // from a notification or a widget without a biometric prompt first, and the threat this
                // defends against is a file being edited, not the phone being unlocked.
                .build(),
        )
        return generator.generateKey()
    }

    private companion object {
        const val TAG = "DeskPairSecrets"
        const val FILE = "deskpair-secrets"
        const val KEYSTORE = "AndroidKeyStore"
        const val ALIAS = "deskpair-secrets-v1"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val IV_BYTES = 12
        const val TAG_BITS = 128
    }
}

/**
 * The settings file, in the app's own storage.
 *
 * A plain file rather than SharedPreferences because the shared module already owns the shape of the
 * document, and one JSON file is something a support request can ask someone to read out.
 */
class AndroidSettingsStorage(context: Context) : SettingsStorage {

    private val file = File(context.applicationContext.filesDir, "settings.json")

    /** Shown in the About section, so a support request can ask for it by name. */
    val path: String get() = file.absolutePath

    override fun read(): String? = if (file.exists()) file.readText() else null

    override fun write(text: String) {
        // Written beside and moved into place, so a process killed mid-write leaves the previous settings
        // rather than half of the new ones. HostConfigStore does the same on the desktop.
        val temporary = File(file.parentFile, "${file.name}.tmp")
        temporary.writeText(text)
        if (!temporary.renameTo(file)) {
            file.writeText(text)
            temporary.delete()
        }
    }
}
