using DeskPair.Platform.Abstractions.Input;

namespace DeskPair.Platform.Windows.Input;

internal static class VirtualKeys
{
    public static ushort FromControlKey(ControlKey key) => key switch
    {
        ControlKey.Alt => 0x12,
        ControlKey.Backspace => 0x08,
        ControlKey.CapsLock => 0x14,
        ControlKey.Control => 0x11,
        ControlKey.Delete => 0x2E,
        ControlKey.DownArrow => 0x28,
        ControlKey.End => 0x23,
        ControlKey.Escape => 0x1B,
        ControlKey.F1 => 0x70,
        ControlKey.F2 => 0x71,
        ControlKey.F3 => 0x72,
        ControlKey.F4 => 0x73,
        ControlKey.F5 => 0x74,
        ControlKey.F6 => 0x75,
        ControlKey.F7 => 0x76,
        ControlKey.F8 => 0x77,
        ControlKey.F9 => 0x78,
        ControlKey.F10 => 0x79,
        ControlKey.F11 => 0x7A,
        ControlKey.F12 => 0x7B,
        ControlKey.Home => 0x24,
        ControlKey.LeftArrow => 0x25,
        ControlKey.Meta => 0x5B,
        ControlKey.PageDown => 0x22,
        ControlKey.PageUp => 0x21,
        ControlKey.Return => 0x0D,
        ControlKey.RightArrow => 0x27,
        ControlKey.Shift => 0x10,
        ControlKey.Space => 0x20,
        ControlKey.Tab => 0x09,
        ControlKey.UpArrow => 0x26,
        ControlKey.Numpad0 => 0x60,
        ControlKey.Numpad1 => 0x61,
        ControlKey.Numpad2 => 0x62,
        ControlKey.Numpad3 => 0x63,
        ControlKey.Numpad4 => 0x64,
        ControlKey.Numpad5 => 0x65,
        ControlKey.Numpad6 => 0x66,
        ControlKey.Numpad7 => 0x67,
        ControlKey.Numpad8 => 0x68,
        ControlKey.Numpad9 => 0x69,
        ControlKey.NumpadEnter => 0x0D,
        ControlKey.Multiply => 0x6A,
        ControlKey.Add => 0x6B,
        ControlKey.Subtract => 0x6D,
        ControlKey.Decimal => 0x6E,
        ControlKey.Divide => 0x6F,
        ControlKey.Insert => 0x2D,
        ControlKey.Pause => 0x13,
        ControlKey.PrintScreen => 0x2C,
        ControlKey.ScrollLock => 0x91,
        ControlKey.NumLock => 0x90,
        ControlKey.Menu => 0x5D,
        ControlKey.RightShift => 0xA1,
        ControlKey.RightControl => 0xA3,
        ControlKey.RightAlt => 0xA5,
        ControlKey.RightMeta => 0x5C,
        ControlKey.VolumeMute => 0xAD,
        ControlKey.VolumeUp => 0xAF,
        ControlKey.VolumeDown => 0xAE,
        _ => 0,
    };

    /// <summary>Keys that need the extended flag even when MapVirtualKey does not say so.</summary>
    public static bool IsExtended(ushort vk) => vk is 0x21 or 0x22 or 0x23 or 0x24 or 0x25 or 0x26 or 0x27 or 0x28 or 0x2D or 0x2E or 0x5B or 0x5C or 0x5D or 0xA3 or 0xA5 or 0x6F or 0x90 or 0x2C;
}
